/* Generated by Yosys 0.62 (git sha1 v0.62, g++ 15.2.0 -fPIC -O3) */

module bissc_Barch(clk_i, rst_i, go_i, half_clk_period_i, n_rising_edges_i, data_i, pos_o, valid_o, err_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input data_i;
  wire data_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  output clk_o;
  wire clk_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [50:0] _4_;
  wire _5_;
  wire _6_;
  wire clock_done;
  wire data;
  wire samp;
  bissc_capture_Brtl bissc_capture_inst (
    .clk_i(clk_i),
    .data_i(data),
    .done_i(clock_done),
    .err_o(_6_),
    .go_i(go_i),
    .pos_o(_4_),
    .rst_i(rst_i),
    .samp_i(samp),
    .valid_o(_5_)
  );
  bissc_extended_clock_Brtl bissc_extended_clock_inst (
    .clk_i(clk_i),
    .clk_o(_3_),
    .data_i(data_i),
    .data_o(_2_),
    .done_o(_0_),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i),
    .samp_o(_1_)
  );
  assign clock_done = _0_;
  assign data = _2_;
  assign samp = _1_;
  assign pos_o = _4_;
  assign valid_o = _5_;
  assign err_o = _6_;
  assign clk_o = _3_;
endmodule

module bissc_capture_Brtl(clk_i, rst_i, go_i, samp_i, data_i, done_i, pos_o, valid_o, err_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input samp_i;
  wire samp_i;
  input data_i;
  wire data_i;
  input done_i;
  wire done_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [2:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [5:0] _11_;
  wire [58:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [50:0] _17_;
  wire _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire [50:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  wire [2:0] _26_;
  wire [5:0] _27_;
  wire [58:0] _28_;
  wire [50:0] _29_;
  wire _30_;
  wire _31_;
  wire [1:0] _32_;
  wire [2:0] _33_;
  wire [5:0] _34_;
  wire [58:0] _35_;
  reg [50:0] _36_;
  reg _37_;
  reg _38_;
  reg [1:0] _39_;
  reg [2:0] _40_;
  reg [5:0] _41_;
  reg [58:0] _42_;
  wire [5:0] crc;
  wire [2:0] initial_bits;
  wire [58:0] shift_pos;
  wire [1:0] state;
  assign _00_ = go_i ? 2'h1 : state;
  assign _01_ = state == 2'h0;
  assign _02_ = done_i ? 1'h1 : 1'h0;
  assign _03_ = done_i ? 2'h0 : state;
  assign _04_ = { initial_bits[1:0], data_i } == 3'h2;
  assign _05_ = _06_ ? 2'h2 : _03_;
  assign _06_ = _04_ & samp_i;
  assign _07_ = samp_i ? { initial_bits[1:0], data_i } : initial_bits;
  assign _08_ = state == 2'h1;
  assign _09_ = crc[0] ^ crc[5];
  assign _10_ = data_i ^ crc[5];
  assign _11_ = samp_i ? { crc[4:1], _09_, _10_ } : crc;
  assign _12_ = samp_i ? { shift_pos[57:0], data_i } : shift_pos;
  assign _13_ = crc != 6'h3f;
  assign _14_ = ~ shift_pos[7];
  assign _15_ = _13_ | _14_;
  assign _16_ = _15_ ? 1'h1 : 1'h0;
  assign _17_ = done_i ? shift_pos[58:8] : _36_;
  assign _18_ = done_i ? 1'h1 : 1'h0;
  assign _19_ = done_i ? _16_ : 1'h0;
  assign _20_ = done_i ? 2'h0 : state;
  assign _21_ = state == 2'h2;
  function [50:0] \:612 ;
    input [50:0] a;
    input [152:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:612  = b[50:0];
      3'b?1?:
        \:612  = b[101:51];
      3'b1??:
        \:612  = b[152:102];
      default:
        \:612  = a;
    endcase
  endfunction
  assign _22_ = \:612 (51'hxxxxxxxxxxxxx, { _17_, _36_, _36_ }, { _21_, _08_, _01_ });
  function [0:0] \:615 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:615  = b[0:0];
      3'b?1?:
        \:615  = b[1:1];
      3'b1??:
        \:615  = b[2:2];
      default:
        \:615  = a;
    endcase
  endfunction
  assign _23_ = \:615 (1'hx, { _18_, 2'h0 }, { _21_, _08_, _01_ });
  function [0:0] \:618 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:618  = b[0:0];
      3'b?1?:
        \:618  = b[1:1];
      3'b1??:
        \:618  = b[2:2];
      default:
        \:618  = a;
    endcase
  endfunction
  assign _24_ = \:618 (1'hx, { _19_, _02_, 1'h0 }, { _21_, _08_, _01_ });
  function [1:0] \:620 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:620  = b[1:0];
      3'b?1?:
        \:620  = b[3:2];
      3'b1??:
        \:620  = b[5:4];
      default:
        \:620  = a;
    endcase
  endfunction
  assign _25_ = \:620 (2'hx, { _20_, _05_, _00_ }, { _21_, _08_, _01_ });
  function [2:0] \:623 ;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:623  = b[2:0];
      3'b?1?:
        \:623  = b[5:3];
      3'b1??:
        \:623  = b[8:6];
      default:
        \:623  = a;
    endcase
  endfunction
  assign _26_ = \:623 (3'hx, { initial_bits, _07_, 3'h0 }, { _21_, _08_, _01_ });
  function [5:0] \:626 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:626  = b[5:0];
      3'b?1?:
        \:626  = b[11:6];
      3'b1??:
        \:626  = b[17:12];
      default:
        \:626  = a;
    endcase
  endfunction
  assign _27_ = \:626 (6'hxx, { _11_, crc, 6'h00 }, { _21_, _08_, _01_ });
  function [58:0] \:629 ;
    input [58:0] a;
    input [176:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:629  = b[58:0];
      3'b?1?:
        \:629  = b[117:59];
      3'b1??:
        \:629  = b[176:118];
      default:
        \:629  = a;
    endcase
  endfunction
  assign _28_ = \:629 (59'hxxxxxxxxxxxxxxx, { _12_, shift_pos, 59'h000000000000000 }, { _21_, _08_, _01_ });
  assign _29_ = rst_i ? _36_ : _22_;
  assign _30_ = rst_i ? 1'h0 : _23_;
  assign _31_ = rst_i ? 1'h0 : _24_;
  assign _32_ = rst_i ? 2'h0 : _25_;
  assign _33_ = rst_i ? initial_bits : _26_;
  assign _34_ = rst_i ? crc : _27_;
  assign _35_ = rst_i ? shift_pos : _28_;
  always @(posedge clk_i)
    _36_ <= _29_;
  always @(posedge clk_i)
    _37_ <= _30_;
  always @(posedge clk_i)
    _38_ <= _31_;
  always @(posedge clk_i)
    _39_ <= _32_;
  always @(posedge clk_i)
    _40_ <= _33_;
  always @(posedge clk_i)
    _41_ <= _34_;
  always @(posedge clk_i)
    _42_ <= _35_;
  assign state = _39_;
  assign initial_bits = _40_;
  assign crc = _41_;
  assign shift_pos = _42_;
  assign pos_o = _36_;
  assign valid_o = _37_;
  assign err_o = _38_;
endmodule

module bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire _09_;
  wire [1:0] _10_;
  wire [5:0] _11_;
  wire _12_;
  wire _13_;
  wire [5:0] _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire [7:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [1:0] _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire [7:0] _28_;
  wire [1:0] _29_;
  wire [5:0] _30_;
  wire _31_;
  wire _32_;
  wire [7:0] _33_;
  wire [1:0] _34_;
  wire [5:0] _35_;
  reg _36_;
  reg _37_;
  reg [7:0] _38_;
  reg [1:0] _39_;
  reg [5:0] _40_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _36_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _37_;
  assign _06_ = ~ _37_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 1'h0 : _36_;
  assign _10_ = _19_ ? 2'h0 : clock_state;
  assign _11_ = _07_ ? rising_counter : _08_;
  assign _12_ = _07_ & _06_;
  assign _13_ = _07_ & _06_;
  assign _14_ = _20_ ? _11_ : rising_counter;
  assign _15_ = clock_timer - 8'h01;
  assign _16_ = _12_ & _04_;
  assign _17_ = _04_ ? _05_ : _37_;
  assign _18_ = _04_ ? half_clk_period_i : _15_;
  assign _19_ = _13_ & _04_;
  assign _20_ = _06_ & _04_;
  assign _21_ = clock_state == 2'h1;
  assign _22_ = data_i | go_i;
  assign _23_ = _22_ ? 1'h0 : _36_;
  assign _24_ = _22_ ? 2'h0 : clock_state;
  assign _25_ = clock_state == 2'h2;
  function [0:0] \:772 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:772  = b[0:0];
      3'b?1?:
        \:772  = b[1:1];
      3'b1??:
        \:772  = b[2:2];
      default:
        \:772  = a;
    endcase
  endfunction
  assign _26_ = \:772 (_36_, { _23_, _09_, _00_ }, { _25_, _21_, _03_ });
  function [0:0] \:773 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:773  = b[0:0];
      3'b?1?:
        \:773  = b[1:1];
      3'b1??:
        \:773  = b[2:2];
      default:
        \:773  = a;
    endcase
  endfunction
  assign _27_ = \:773 (_37_, { _37_, _17_, _01_ }, { _25_, _21_, _03_ });
  function [7:0] \:774 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:774  = b[7:0];
      3'b?1?:
        \:774  = b[15:8];
      3'b1??:
        \:774  = b[23:16];
      default:
        \:774  = a;
    endcase
  endfunction
  assign _28_ = \:774 (clock_timer, { clock_timer, _18_, half_clk_period_i }, { _25_, _21_, _03_ });
  function [1:0] \:775 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:775  = b[1:0];
      3'b?1?:
        \:775  = b[3:2];
      3'b1??:
        \:775  = b[5:4];
      default:
        \:775  = a;
    endcase
  endfunction
  assign _29_ = \:775 (clock_state, { _24_, _10_, _02_ }, { _25_, _21_, _03_ });
  function [5:0] \:776 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:776  = b[5:0];
      3'b?1?:
        \:776  = b[11:6];
      3'b1??:
        \:776  = b[17:12];
      default:
        \:776  = a;
    endcase
  endfunction
  assign _30_ = \:776 (rising_counter, { rising_counter, _14_, n_rising_edges_i }, { _25_, _21_, _03_ });
  assign _31_ = rst_i ? 1'h0 : _26_;
  assign _32_ = rst_i ? _37_ : _27_;
  assign _33_ = rst_i ? clock_timer : _28_;
  assign _34_ = rst_i ? 2'h0 : _29_;
  assign _35_ = rst_i ? rising_counter : _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  always @(posedge clk_i)
    _38_ <= _33_;
  always @(posedge clk_i)
    _39_ <= _34_;
  always @(posedge clk_i)
    _40_ <= _35_;
  assign clock_timer = _38_;
  assign clock_state = _39_;
  assign rising_counter = _40_;
  assign busy_o = _36_;
  assign clk_o = _37_;
endmodule

module bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire [1:0] _09_;
  wire [5:0] _10_;
  wire _11_;
  wire [5:0] _12_;
  wire [7:0] _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire [1:0] _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [7:0] _25_;
  wire [1:0] _26_;
  wire [5:0] _27_;
  wire _28_;
  wire _29_;
  wire [7:0] _30_;
  wire [1:0] _31_;
  wire [5:0] _32_;
  reg _33_;
  reg _34_;
  reg [7:0] _35_;
  reg [1:0] _36_;
  reg [5:0] _37_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _33_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _34_;
  assign _06_ = ~ _34_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 2'h2 : clock_state;
  assign _10_ = _07_ ? rising_counter : _08_;
  assign _11_ = _07_ & _06_;
  assign _12_ = _17_ ? _10_ : rising_counter;
  assign _13_ = clock_timer - 8'h01;
  assign _14_ = _04_ ? _05_ : _34_;
  assign _15_ = _04_ ? half_clk_period_i : _13_;
  assign _16_ = _11_ & _04_;
  assign _17_ = _06_ & _04_;
  assign _18_ = clock_state == 2'h1;
  assign _19_ = data_i | go_i;
  assign _20_ = _19_ ? 1'h0 : _33_;
  assign _21_ = _19_ ? 2'h0 : clock_state;
  assign _22_ = clock_state == 2'h2;
  function [0:0] \:703 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:703  = b[0:0];
      3'b?1?:
        \:703  = b[1:1];
      3'b1??:
        \:703  = b[2:2];
      default:
        \:703  = a;
    endcase
  endfunction
  assign _23_ = \:703 (_33_, { _20_, _33_, _00_ }, { _22_, _18_, _03_ });
  function [0:0] \:704 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:704  = b[0:0];
      3'b?1?:
        \:704  = b[1:1];
      3'b1??:
        \:704  = b[2:2];
      default:
        \:704  = a;
    endcase
  endfunction
  assign _24_ = \:704 (_34_, { _34_, _14_, _01_ }, { _22_, _18_, _03_ });
  function [7:0] \:705 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:705  = b[7:0];
      3'b?1?:
        \:705  = b[15:8];
      3'b1??:
        \:705  = b[23:16];
      default:
        \:705  = a;
    endcase
  endfunction
  assign _25_ = \:705 (clock_timer, { clock_timer, _15_, half_clk_period_i }, { _22_, _18_, _03_ });
  function [1:0] \:706 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:706  = b[1:0];
      3'b?1?:
        \:706  = b[3:2];
      3'b1??:
        \:706  = b[5:4];
      default:
        \:706  = a;
    endcase
  endfunction
  assign _26_ = \:706 (clock_state, { _21_, _09_, _02_ }, { _22_, _18_, _03_ });
  function [5:0] \:707 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:707  = b[5:0];
      3'b?1?:
        \:707  = b[11:6];
      3'b1??:
        \:707  = b[17:12];
      default:
        \:707  = a;
    endcase
  endfunction
  assign _27_ = \:707 (rising_counter, { rising_counter, _12_, n_rising_edges_i }, { _22_, _18_, _03_ });
  assign _28_ = rst_i ? 1'h0 : _23_;
  assign _29_ = rst_i ? _34_ : _24_;
  assign _30_ = rst_i ? clock_timer : _25_;
  assign _31_ = rst_i ? 2'h0 : _26_;
  assign _32_ = rst_i ? rising_counter : _27_;
  always @(posedge clk_i)
    _33_ <= _28_;
  always @(posedge clk_i)
    _34_ <= _29_;
  always @(posedge clk_i)
    _35_ <= _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  assign clock_timer = _35_;
  assign clock_state = _36_;
  assign rising_counter = _37_;
  assign busy_o = _33_;
  assign clk_o = _34_;
endmodule

module bissc_extended_clock_Brtl(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, done_o, samp_o, data_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output done_o;
  wire done_o;
  output samp_o;
  wire samp_o;
  output data_o;
  wire data_o;
  output clk_o;
  wire clk_o;
  wire [5:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [1:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [1:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [1:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  reg _26_;
  reg _27_;
  reg _28_;
  reg [1:0] _29_ = 2'h0;
  reg _30_;
  reg _31_;
  wire busy1;
  wire busy2;
  wire data_dly;
  wire data_dly2;
  wire go2;
  wire [5:0] nbits;
  wire samp_clk;
  wire samp_clk_dly;
  wire samp_clk_rise;
  wire [1:0] state;
  assign _00_ = n_rising_edges_i - 6'h02;
  assign _05_ = ~ samp_clk_dly;
  assign _06_ = samp_clk & _05_;
  assign _07_ = go_i ? 2'h1 : state;
  assign _08_ = state == 2'h0;
  assign _09_ = ~ data_i;
  assign _10_ = go_i ? 2'h2 : state;
  assign _11_ = _09_ ? 1'h1 : 1'h0;
  assign _12_ = _09_ ? 2'h2 : _10_;
  assign _13_ = state == 2'h1;
  assign _14_ = ~ busy1;
  assign _15_ = ~ busy2;
  assign _16_ = _14_ & _15_;
  assign _17_ = _16_ ? 1'h1 : 1'h0;
  assign _18_ = _16_ ? 2'h0 : state;
  assign _19_ = state == 2'h2;
  function [0:0] \:529 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:529  = b[0:0];
      3'b?1?:
        \:529  = b[1:1];
      3'b1??:
        \:529  = b[2:2];
      default:
        \:529  = a;
    endcase
  endfunction
  assign _20_ = \:529 (1'h0, { _17_, 2'h0 }, { _19_, _13_, _08_ });
  function [0:0] \:532 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:532  = b[0:0];
      3'b?1?:
        \:532  = b[1:1];
      3'b1??:
        \:532  = b[2:2];
      default:
        \:532  = a;
    endcase
  endfunction
  assign _21_ = \:532 (1'h0, { 1'h0, _11_, 1'h0 }, { _19_, _13_, _08_ });
  function [1:0] \:533 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:533  = b[1:0];
      3'b?1?:
        \:533  = b[3:2];
      3'b1??:
        \:533  = b[5:4];
      default:
        \:533  = a;
    endcase
  endfunction
  assign _22_ = \:533 (state, { _18_, _12_, _07_ }, { _19_, _13_, _08_ });
  assign _23_ = rst_i ? _26_ : _20_;
  assign _24_ = rst_i ? 1'h0 : _21_;
  assign _25_ = rst_i ? 2'h0 : _22_;
  always @(posedge clk_i)
    _26_ <= _23_;
  always @(posedge clk_i)
    _27_ <= samp_clk;
  always @(posedge clk_i)
    _28_ <= _24_;
  always @(posedge clk_i)
    _29_ <= _25_;
  always @(posedge clk_i)
    _30_ <= data_i;
  always @(posedge clk_i)
    _31_ <= data_dly;
  bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e bissc_clock_inst (
    .busy_o(_01_),
    .clk_i(clk_i),
    .clk_o(_02_),
    .data_i(data_i),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i)
  );
  bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9 bissc_samp_clock_inst (
    .busy_o(_03_),
    .clk_i(clk_i),
    .clk_o(_04_),
    .data_i(data_i),
    .go_i(go2),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(nbits),
    .rst_i(rst_i)
  );
  assign nbits = _00_;
  assign samp_clk = _04_;
  assign samp_clk_dly = _27_;
  assign samp_clk_rise = _06_;
  assign go2 = _28_;
  assign state = _29_;
  assign data_dly = _30_;
  assign data_dly2 = _31_;
  assign busy1 = _01_;
  assign busy2 = _03_;
  assign done_o = _26_;
  assign samp_o = samp_clk_rise;
  assign data_o = data_dly2;
  assign clk_o = _02_;
endmodule

module pulse_stretch_Brtl(clk_i, rst_i, width_i, trig_i, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  input trig_i;
  wire trig_i;
  output pulse_o;
  wire pulse_o;
  wire _00_;
  wire _01_;
  wire [25:0] _02_;
  wire [25:0] _03_;
  wire _04_;
  wire [25:0] _05_;
  wire _06_;
  wire [25:0] _07_;
  wire _08_;
  reg [25:0] _09_;
  reg _10_;
  wire pulse;
  wire [25:0] pulse_timer;
  assign _00_ = pulse | trig_i;
  assign _01_ = pulse_timer != 26'h0000000;
  assign _02_ = pulse_timer - 26'h0000001;
  assign _03_ = _01_ ? _02_ : pulse_timer;
  assign _04_ = _01_ ? 1'h1 : 1'h0;
  assign _05_ = trig_i ? width_i : _03_;
  assign _06_ = trig_i ? 1'h1 : _04_;
  assign _07_ = rst_i ? 26'h0000000 : _05_;
  assign _08_ = rst_i ? 1'h0 : _06_;
  always @(posedge clk_i)
    _09_ <= _07_;
  always @(posedge clk_i)
    _10_ <= _08_;
  assign pulse_timer = _09_;
  assign pulse = _10_;
  assign pulse_o = _00_;
endmodule

module pulsed_trigger_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, width_i, busy_o, trig_o, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  output pulse_o;
  wire pulse_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire busy;
  wire trig;
  assign _0_ = busy | _1_;
  pulse_stretch_Brtl pulse_stretch_inst (
    .clk_i(clk_i),
    .pulse_o(_1_),
    .rst_i(rst_i),
    .trig_i(trig),
    .width_i(width_i)
  );
  trigger_generator_Brtl trig_gen_inst (
    .busy_o(_2_),
    .clk_i(clk_i),
    .go_i(go_i),
    .ntrig_i(ntrig_i),
    .rst_i(rst_i),
    .trig_o(_3_),
    .trig_period_i(trig_period_i)
  );
  assign trig = _3_;
  assign busy = _2_;
  assign busy_o = _0_;
  assign trig_o = trig;
  assign pulse_o = _1_;
endmodule

module spi_registers_Brtl(clk_i, rst_i, cs_i, sck_i, rx_i, trig_i, pos_i, pos_valid_i, error_event_i, io_in_i, tx_o, override_trig_o, ntrig_o, trig_period_o, width_o, pos_req_o, acq_start_o, bissc_half_clk_period_o, bissc_n_rising_edges_o, io_dir_o, io_out_o
);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input cs_i;
  wire cs_i;
  input sck_i;
  wire sck_i;
  input rx_i;
  wire rx_i;
  input trig_i;
  wire trig_i;
  input [50:0] pos_i;
  wire [50:0] pos_i;
  input pos_valid_i;
  wire pos_valid_i;
  input error_event_i;
  wire error_event_i;
  input [5:0] io_in_i;
  wire [5:0] io_in_i;
  output tx_o;
  wire tx_o;
  output override_trig_o;
  wire override_trig_o;
  output [31:0] ntrig_o;
  wire [31:0] ntrig_o;
  output [31:0] trig_period_o;
  wire [31:0] trig_period_o;
  output [25:0] width_o;
  wire [25:0] width_o;
  output pos_req_o;
  wire pos_req_o;
  output acq_start_o;
  wire acq_start_o;
  output [7:0] bissc_half_clk_period_o;
  wire [7:0] bissc_half_clk_period_o;
  output [5:0] bissc_n_rising_edges_o;
  wire [5:0] bissc_n_rising_edges_o;
  output [5:0] io_dir_o;
  wire [5:0] io_dir_o;
  output [5:0] io_out_o;
  wire [5:0] io_out_o;
  wire [5:0] _000_;
  wire _001_;
  wire [31:0] _002_;
  wire _003_;
  wire _004_;
  wire [31:0] _005_;
  wire [31:0] _006_;
  wire [25:0] _007_;
  wire _008_;
  wire _009_;
  wire [7:0] _010_;
  wire [5:0] _011_;
  wire [5:0] _012_;
  wire [5:0] _013_;
  wire [31:0] _014_;
  wire [39:0] _015_;
  wire [5:0] _016_;
  wire _017_;
  wire [5:0] _018_;
  wire [5:0] _019_;
  wire _020_;
  wire _021_;
  wire [31:0] _022_;
  wire [31:0] _023_;
  wire [25:0] _024_;
  wire _025_;
  wire _026_;
  wire [7:0] _027_;
  wire [5:0] _028_;
  wire [5:0] _029_;
  wire [5:0] _030_;
  wire [31:0] _031_;
  wire [39:0] _032_;
  wire [5:0] _033_;
  wire _034_;
  wire [5:0] _035_;
  wire [5:0] _036_;
  wire _037_;
  wire _038_;
  wire [31:0] _039_;
  wire [31:0] _040_;
  wire [25:0] _041_;
  wire _042_;
  wire _043_;
  wire [7:0] _044_;
  wire [5:0] _045_;
  wire [5:0] _046_;
  wire [5:0] _047_;
  wire [31:0] _048_;
  wire [39:0] _049_;
  wire [5:0] _050_;
  wire [7:0] _051_;
  wire _052_;
  wire [5:0] _053_;
  wire [5:0] _054_;
  wire [7:0] _055_;
  wire [7:0] _056_;
  wire _057_;
  wire _058_;
  wire [5:0] _059_;
  wire [5:0] _060_;
  reg _061_;
  reg _062_;
  reg [31:0] _063_;
  reg [31:0] _064_;
  reg [25:0] _065_;
  reg _066_;
  reg _067_;
  reg [7:0] _068_;
  reg [5:0] _069_;
  reg [5:0] _070_;
  reg [5:0] _071_;
  reg [31:0] _072_;
  reg [39:0] _073_;
  reg _074_;
  reg [5:0] _075_;
  reg [7:0] _076_;
  reg [7:0] _077_;
  reg [15:0] _078_;
  reg _079_;
  reg [5:0] _080_;
  reg [5:0] _081_;
  wire [5:0] _082_;
  reg [5:0] _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire [15:0] _091_;
  wire [15:0] _092_;
  wire [7:0] _093_;
  wire [7:0] _094_;
  wire [7:0] _095_;
  wire [15:0] _096_;
  wire [5:0] _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire [5:0] _110_;
  wire [1:0] _111_;
  wire [17:0] _112_;
  wire [5:0] _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire [31:0] _125_;
  wire [31:0] _126_;
  wire [25:0] _127_;
  wire _128_;
  wire _129_;
  wire [7:0] _130_;
  wire [5:0] _131_;
  wire [5:0] _132_;
  wire [5:0] _133_;
  wire [5:0] _134_;
  wire [5:0] _135_;
  wire _136_;
  wire [31:0] _137_;
  wire [31:0] _138_;
  wire [25:0] _139_;
  wire _140_;
  wire _141_;
  wire [7:0] _142_;
  wire [5:0] _143_;
  wire [5:0] _144_;
  wire [5:0] _145_;
  wire [5:0] _146_;
  wire [5:0] _147_;
  wire _148_;
  wire [31:0] _149_;
  wire [31:0] _150_;
  wire [25:0] _151_;
  wire _152_;
  wire _153_;
  wire [7:0] _154_;
  wire [5:0] _155_;
  wire [5:0] _156_;
  wire [5:0] _157_;
  wire [31:0] _158_;
  wire _159_;
  wire [5:0] _160_;
  wire [5:0] bit_counter;
  wire cs;
  wire [39:0] datain;
  wire [31:0] dataout;
  wire [5:0] io_dir;
  wire [5:0] io_in;
  wire [5:0] io_out;
  wire [7:0] n_err;
  wire [7:0] n_over;
  wire [15:0] n_pos;
  wire new_pos;
  wire rx;
  wire sck;
  wire sck_fall;
  wire sck_prev;
  wire sck_rise;
  assign _106_ = { datain[6:0], rx } == 8'h07;
  assign _107_ = { datain[6:0], rx } == 8'h08;
  assign _108_ = { datain[6:0], rx } == 8'h0a;
  assign _109_ = { datain[6:0], rx } == 8'h0b;
  function [5:0] \:121 ;
    input [5:0] a;
    input [65:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:121  = b[5:0];
      11'b?????????1?:
        \:121  = b[11:6];
      11'b????????1??:
        \:121  = b[17:12];
      11'b???????1???:
        \:121  = b[23:18];
      11'b??????1????:
        \:121  = b[29:24];
      11'b?????1?????:
        \:121  = b[35:30];
      11'b????1??????:
        \:121  = b[41:36];
      11'b???1???????:
        \:121  = b[47:42];
      11'b??1????????:
        \:121  = b[53:48];
      11'b?1?????????:
        \:121  = b[59:54];
      11'b1??????????:
        \:121  = b[65:60];
      default:
        \:121  = a;
    endcase
  endfunction
  assign _110_ = \:121 (6'h00, { io_in_i, io_in, pos_i[24:19], _069_, _068_[5:0], _065_[5:0], _063_[5:0], _064_[5:0], pos_i[5:0], n_pos[5:0], 6'h1c }, { _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_ });
  function [1:0] \:134 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:134  = b[1:0];
      11'b?????????1?:
        \:134  = b[3:2];
      11'b????????1??:
        \:134  = b[5:4];
      11'b???????1???:
        \:134  = b[7:6];
      11'b??????1????:
        \:134  = b[9:8];
      11'b?????1?????:
        \:134  = b[11:10];
      11'b????1??????:
        \:134  = b[13:12];
      11'b???1???????:
        \:134  = b[15:14];
      11'b??1????????:
        \:134  = b[17:16];
      11'b?1?????????:
        \:134  = b[19:18];
      11'b1??????????:
        \:134  = b[21:20];
      default:
        \:134  = a;
    endcase
  endfunction
  assign _111_ = \:134 (2'h0, { 4'h0, pos_i[26:25], 2'h0, _068_[7:6], _065_[7:6], _063_[7:6], _064_[7:6], pos_i[7:6], n_pos[7:6], 2'h0 }, { _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_ });
  function [17:0] \:147 ;
    input [17:0] a;
    input [197:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:147  = b[17:0];
      11'b?????????1?:
        \:147  = b[35:18];
      11'b????????1??:
        \:147  = b[53:36];
      11'b???????1???:
        \:147  = b[71:54];
      11'b??????1????:
        \:147  = b[89:72];
      11'b?????1?????:
        \:147  = b[107:90];
      11'b????1??????:
        \:147  = b[125:108];
      11'b???1???????:
        \:147  = b[143:126];
      11'b??1????????:
        \:147  = b[161:144];
      11'b?1?????????:
        \:147  = b[179:162];
      11'b1??????????:
        \:147  = b[197:180];
      default:
        \:147  = a;
    endcase
  endfunction
  assign _112_ = \:147 (18'h00000, { 36'h000000000, pos_i[44:27], 36'h000000000, _065_[25:8], _063_[25:8], _064_[25:8], pos_i[25:8], n_over[1:0], n_err, n_pos[15:8], 18'h2fea5 }, { _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_ });
  function [5:0] \:159 ;
    input [5:0] a;
    input [65:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:159  = b[5:0];
      11'b?????????1?:
        \:159  = b[11:6];
      11'b????????1??:
        \:159  = b[17:12];
      11'b???????1???:
        \:159  = b[23:18];
      11'b??????1????:
        \:159  = b[29:24];
      11'b?????1?????:
        \:159  = b[35:30];
      11'b????1??????:
        \:159  = b[41:36];
      11'b???1???????:
        \:159  = b[47:42];
      11'b??1????????:
        \:159  = b[53:48];
      11'b?1?????????:
        \:159  = b[59:54];
      11'b1??????????:
        \:159  = b[65:60];
      default:
        \:159  = a;
    endcase
  endfunction
  assign _113_ = \:159 (6'h00, { 12'h000, pos_i[50:45], 18'h00000, _063_[31:26], _064_[31:26], pos_i[31:26], n_over[7:2], 6'h32 }, { _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_ });
  function [0:0] \:161 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:161  = b[0:0];
      11'b?????????1?:
        \:161  = b[1:1];
      11'b????????1??:
        \:161  = b[2:2];
      11'b???????1???:
        \:161  = b[3:3];
      11'b??????1????:
        \:161  = b[4:4];
      11'b?????1?????:
        \:161  = b[5:5];
      11'b????1??????:
        \:161  = b[6:6];
      11'b???1???????:
        \:161  = b[7:7];
      11'b??1????????:
        \:161  = b[8:8];
      11'b?1?????????:
        \:161  = b[9:9];
      11'b1??????????:
        \:161  = b[10:10];
      default:
        \:161  = a;
    endcase
  endfunction
  assign _114_ = \:161 (new_pos, { new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, 1'h0, new_pos, new_pos }, { _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_ });
  assign _115_ = bit_counter == 6'h27;
  assign _116_ = datain[38:31] == 8'h83;
  assign _117_ = datain[38:31] == 8'h84;
  assign _118_ = datain[38:31] == 8'h85;
  assign _119_ = datain[38:31] == 8'h86;
  assign _120_ = datain[38:31] == 8'h87;
  assign _121_ = datain[38:31] == 8'h89;
  assign _122_ = datain[38:31] == 8'h8a;
  assign _123_ = datain[38:31] == 8'h8b;
  function [0:0] \:195 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:195  = b[0:0];
      8'b??????1?:
        \:195  = b[1:1];
      8'b?????1??:
        \:195  = b[2:2];
      8'b????1???:
        \:195  = b[3:3];
      8'b???1????:
        \:195  = b[4:4];
      8'b??1?????:
        \:195  = b[5:5];
      8'b?1??????:
        \:195  = b[6:6];
      8'b1???????:
        \:195  = b[7:7];
      default:
        \:195  = a;
    endcase
  endfunction
  assign _124_ = \:195 (1'h0, { 2'h0, datain[1], 5'h00 }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [31:0] \:196 ;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:196  = b[31:0];
      8'b??????1?:
        \:196  = b[63:32];
      8'b?????1??:
        \:196  = b[95:64];
      8'b????1???:
        \:196  = b[127:96];
      8'b???1????:
        \:196  = b[159:128];
      8'b??1?????:
        \:196  = b[191:160];
      8'b?1??????:
        \:196  = b[223:192];
      8'b1???????:
        \:196  = b[255:224];
      default:
        \:196  = a;
    endcase
  endfunction
  assign _125_ = \:196 (_063_, { _063_, _063_, _063_, _063_, _063_, _063_, datain[30:0], rx, _063_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [31:0] \:197 ;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:197  = b[31:0];
      8'b??????1?:
        \:197  = b[63:32];
      8'b?????1??:
        \:197  = b[95:64];
      8'b????1???:
        \:197  = b[127:96];
      8'b???1????:
        \:197  = b[159:128];
      8'b??1?????:
        \:197  = b[191:160];
      8'b?1??????:
        \:197  = b[223:192];
      8'b1???????:
        \:197  = b[255:224];
      default:
        \:197  = a;
    endcase
  endfunction
  assign _126_ = \:197 (_064_, { _064_, _064_, _064_, _064_, _064_, _064_, _064_, datain[30:0], rx }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [25:0] \:198 ;
    input [25:0] a;
    input [207:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:198  = b[25:0];
      8'b??????1?:
        \:198  = b[51:26];
      8'b?????1??:
        \:198  = b[77:52];
      8'b????1???:
        \:198  = b[103:78];
      8'b???1????:
        \:198  = b[129:104];
      8'b??1?????:
        \:198  = b[155:130];
      8'b?1??????:
        \:198  = b[181:156];
      8'b1???????:
        \:198  = b[207:182];
      default:
        \:198  = a;
    endcase
  endfunction
  assign _127_ = \:198 (_065_, { _065_, _065_, _065_, _065_, _065_, datain[24:0], rx, _065_, _065_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [0:0] \:200 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:200  = b[0:0];
      8'b??????1?:
        \:200  = b[1:1];
      8'b?????1??:
        \:200  = b[2:2];
      8'b????1???:
        \:200  = b[3:3];
      8'b???1????:
        \:200  = b[4:4];
      8'b??1?????:
        \:200  = b[5:5];
      8'b?1??????:
        \:200  = b[6:6];
      8'b1???????:
        \:200  = b[7:7];
      default:
        \:200  = a;
    endcase
  endfunction
  assign _128_ = \:200 (1'h0, { 2'h0, rx, 5'h00 }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [0:0] \:202 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:202  = b[0:0];
      8'b??????1?:
        \:202  = b[1:1];
      8'b?????1??:
        \:202  = b[2:2];
      8'b????1???:
        \:202  = b[3:3];
      8'b???1????:
        \:202  = b[4:4];
      8'b??1?????:
        \:202  = b[5:5];
      8'b?1??????:
        \:202  = b[6:6];
      8'b1???????:
        \:202  = b[7:7];
      default:
        \:202  = a;
    endcase
  endfunction
  assign _129_ = \:202 (1'h0, { 2'h0, datain[0], 5'h00 }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [7:0] \:203 ;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:203  = b[7:0];
      8'b??????1?:
        \:203  = b[15:8];
      8'b?????1??:
        \:203  = b[23:16];
      8'b????1???:
        \:203  = b[31:24];
      8'b???1????:
        \:203  = b[39:32];
      8'b??1?????:
        \:203  = b[47:40];
      8'b?1??????:
        \:203  = b[55:48];
      8'b1???????:
        \:203  = b[63:56];
      default:
        \:203  = a;
    endcase
  endfunction
  assign _130_ = \:203 (_068_, { _068_, _068_, _068_, _068_, datain[6:0], rx, _068_, _068_, _068_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [5:0] \:204 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:204  = b[5:0];
      8'b??????1?:
        \:204  = b[11:6];
      8'b?????1??:
        \:204  = b[17:12];
      8'b????1???:
        \:204  = b[23:18];
      8'b???1????:
        \:204  = b[29:24];
      8'b??1?????:
        \:204  = b[35:30];
      8'b?1??????:
        \:204  = b[41:36];
      8'b1???????:
        \:204  = b[47:42];
      default:
        \:204  = a;
    endcase
  endfunction
  assign _131_ = \:204 (_069_, { _069_, _069_, _069_, datain[4:0], rx, _069_, _069_, _069_, _069_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [5:0] \:205 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:205  = b[5:0];
      8'b??????1?:
        \:205  = b[11:6];
      8'b?????1??:
        \:205  = b[17:12];
      8'b????1???:
        \:205  = b[23:18];
      8'b???1????:
        \:205  = b[29:24];
      8'b??1?????:
        \:205  = b[35:30];
      8'b?1??????:
        \:205  = b[41:36];
      8'b1???????:
        \:205  = b[47:42];
      default:
        \:205  = a;
    endcase
  endfunction
  assign _132_ = \:205 (_070_, { datain[12:7], _070_, _070_, _070_, _070_, _070_, _070_, _070_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [5:0] \:206 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:206  = b[5:0];
      8'b??????1?:
        \:206  = b[11:6];
      8'b?????1??:
        \:206  = b[17:12];
      8'b????1???:
        \:206  = b[23:18];
      8'b???1????:
        \:206  = b[29:24];
      8'b??1?????:
        \:206  = b[35:30];
      8'b?1??????:
        \:206  = b[41:36];
      8'b1???????:
        \:206  = b[47:42];
      default:
        \:206  = a;
    endcase
  endfunction
  assign _133_ = \:206 (_071_, { datain[4:0], rx, _071_, _071_, _071_, _071_, _071_, _071_, _071_ }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [5:0] \:207 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:207  = b[5:0];
      8'b??????1?:
        \:207  = b[11:6];
      8'b?????1??:
        \:207  = b[17:12];
      8'b????1???:
        \:207  = b[23:18];
      8'b???1????:
        \:207  = b[29:24];
      8'b??1?????:
        \:207  = b[35:30];
      8'b?1??????:
        \:207  = b[41:36];
      8'b1???????:
        \:207  = b[47:42];
      default:
        \:207  = a;
    endcase
  endfunction
  assign _134_ = \:207 (io_out, { io_out, datain[4:0], rx, io_out, io_out, io_out, io_out, io_out, io_out }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  function [5:0] \:208 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:208  = b[5:0];
      8'b??????1?:
        \:208  = b[11:6];
      8'b?????1??:
        \:208  = b[17:12];
      8'b????1???:
        \:208  = b[23:18];
      8'b???1????:
        \:208  = b[29:24];
      8'b??1?????:
        \:208  = b[35:30];
      8'b?1??????:
        \:208  = b[41:36];
      8'b1???????:
        \:208  = b[47:42];
      default:
        \:208  = a;
    endcase
  endfunction
  assign _135_ = \:208 (io_dir, { io_dir, datain[12:7], io_dir, io_dir, io_dir, io_dir, io_dir, io_dir }, { _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_ });
  assign _136_ = _115_ ? _124_ : 1'h0;
  assign _137_ = _115_ ? _125_ : _063_;
  assign _138_ = _115_ ? _126_ : _064_;
  assign _139_ = _115_ ? _127_ : _065_;
  assign _140_ = _115_ ? _128_ : 1'h0;
  assign _141_ = _115_ ? _129_ : 1'h0;
  assign _142_ = _115_ ? _130_ : _068_;
  assign _143_ = _115_ ? _131_ : _069_;
  assign _144_ = _115_ ? _132_ : _070_;
  assign _145_ = _115_ ? _133_ : _071_;
  assign _146_ = _115_ ? _134_ : io_out;
  assign _147_ = _115_ ? _135_ : io_dir;
  assign _148_ = _098_ ? 1'h0 : _136_;
  assign _149_ = _098_ ? _063_ : _137_;
  assign _150_ = _098_ ? _064_ : _138_;
  assign _151_ = _098_ ? _065_ : _139_;
  assign _152_ = _098_ ? 1'h0 : _140_;
  assign _153_ = _098_ ? 1'h0 : _141_;
  assign _154_ = _098_ ? _068_ : _142_;
  assign _155_ = _098_ ? _069_ : _143_;
  assign _156_ = _098_ ? _070_ : _144_;
  assign _157_ = _098_ ? _071_ : _145_;
  assign _158_ = _098_ ? { _113_, _112_, _111_, _110_ } : dataout;
  assign _159_ = _017_ ? _114_ : new_pos;
  assign _160_ = _098_ ? io_out : _146_;
  assign _000_ = _098_ ? io_dir : _147_;
  assign _001_ = sck_fall ? dataout[31] : _061_;
  assign _002_ = sck_fall ? { dataout[30:0], 1'h0 } : dataout;
  assign _003_ = sck_rise ? _061_ : _001_;
  assign _004_ = sck_rise ? _148_ : 1'h0;
  assign _005_ = sck_rise ? _149_ : _063_;
  assign _006_ = sck_rise ? _150_ : _064_;
  assign _007_ = sck_rise ? _151_ : _065_;
  assign _008_ = sck_rise ? _152_ : 1'h0;
  assign _009_ = sck_rise ? _153_ : 1'h0;
  assign _010_ = sck_rise ? _154_ : _068_;
  assign _011_ = sck_rise ? _155_ : _069_;
  assign _012_ = sck_rise ? _156_ : _070_;
  assign _013_ = sck_rise ? _157_ : _071_;
  assign _014_ = sck_rise ? _158_ : _002_;
  assign _015_ = sck_rise ? { datain[38:0], rx } : datain;
  assign _016_ = sck_rise ? _097_ : bit_counter;
  assign _017_ = _098_ & sck_rise;
  assign _018_ = sck_rise ? _160_ : io_out;
  assign _019_ = sck_rise ? _000_ : io_dir;
  assign _020_ = cs ? _061_ : _003_;
  assign _021_ = cs ? 1'h0 : _004_;
  assign _022_ = cs ? _063_ : _005_;
  assign _023_ = cs ? _064_ : _006_;
  assign _024_ = cs ? _065_ : _007_;
  assign _025_ = cs ? 1'h0 : _008_;
  assign _026_ = cs ? 1'h0 : _009_;
  assign _027_ = cs ? _068_ : _010_;
  assign _028_ = cs ? _069_ : _011_;
  assign _029_ = cs ? _070_ : _012_;
  assign _030_ = cs ? _071_ : _013_;
  assign _031_ = cs ? dataout : _014_;
  assign _032_ = cs ? datain : _015_;
  assign _033_ = cs ? 6'h00 : _016_;
  assign _034_ = cs ? new_pos : _159_;
  assign _035_ = cs ? io_out : _018_;
  assign _036_ = cs ? io_dir : _019_;
  assign _037_ = rst_i ? _061_ : _020_;
  assign _038_ = rst_i ? 1'h0 : _021_;
  assign _039_ = rst_i ? 32'd0 : _022_;
  assign _040_ = rst_i ? 32'd0 : _023_;
  assign _041_ = rst_i ? 26'h0000000 : _024_;
  assign _042_ = rst_i ? 1'h0 : _025_;
  assign _043_ = rst_i ? 1'h0 : _026_;
  assign _044_ = rst_i ? 8'h00 : _027_;
  assign _045_ = rst_i ? 6'h00 : _028_;
  assign _046_ = rst_i ? 6'h00 : _029_;
  assign _047_ = rst_i ? 6'h00 : _030_;
  assign _048_ = rst_i ? 32'd0 : _031_;
  assign _049_ = rst_i ? datain : _032_;
  assign _050_ = rst_i ? bit_counter : _033_;
  assign _051_ = rst_i ? 8'h00 : n_over;
  assign _052_ = rst_i ? 1'h0 : _034_;
  assign _053_ = rst_i ? 6'h00 : _035_;
  assign _054_ = rst_i ? 6'h00 : _036_;
  assign _055_ = n_over + 8'h01;
  assign _056_ = _057_ ? _055_ : _051_;
  assign _057_ = new_pos & pos_valid_i;
  assign _058_ = pos_valid_i ? 1'h1 : _052_;
  assign _059_ = trig_i ? io_dir : _046_;
  assign _060_ = trig_i ? io_out : _047_;
  always @(posedge clk_i)
    _061_ <= _037_;
  always @(posedge clk_i)
    _062_ <= _038_;
  always @(posedge clk_i)
    _063_ <= _039_;
  always @(posedge clk_i)
    _064_ <= _040_;
  always @(posedge clk_i)
    _065_ <= _041_;
  always @(posedge clk_i)
    _066_ <= _042_;
  always @(posedge clk_i)
    _067_ <= _043_;
  always @(posedge clk_i)
    _068_ <= _044_;
  always @(posedge clk_i)
    _069_ <= _045_;
  always @(posedge clk_i)
    _070_ <= _059_;
  always @(posedge clk_i)
    _071_ <= _060_;
  always @(posedge clk_i)
    _072_ <= _048_;
  always @(posedge clk_i)
    _073_ <= _049_;
  always @(posedge clk_i)
    _074_ <= sck;
  always @(posedge clk_i)
    _075_ <= _050_;
  always @(posedge clk_i)
    _076_ <= _095_;
  always @(posedge clk_i)
    _077_ <= _056_;
  always @(posedge clk_i)
    _078_ <= _096_;
  always @(posedge clk_i)
    _079_ <= _058_;
  always @(posedge clk_i)
    _080_ <= _053_;
  always @(posedge clk_i)
    _081_ <= _054_;
  assign _082_ = trig_i ? io_in_i : io_in;
  always @(posedge clk_i)
    _083_ <= _082_;
  assign _087_ = ~ sck;
  assign _088_ = sck_prev & _087_;
  assign _089_ = ~ sck_prev;
  assign _090_ = _089_ & sck;
  assign _091_ = n_pos + 16'h0001;
  assign _092_ = pos_valid_i ? _091_ : n_pos;
  assign _093_ = n_err + 8'h01;
  assign _094_ = error_event_i ? _093_ : n_err;
  assign _095_ = rst_i ? 8'h00 : _094_;
  assign _096_ = rst_i ? 16'h0000 : _092_;
  assign _097_ = bit_counter + 6'h01;
  assign _098_ = bit_counter == 6'h07;
  assign _099_ = { datain[6:0], rx } == 8'h00;
  assign _100_ = { datain[6:0], rx } == 8'h01;
  assign _101_ = { datain[6:0], rx } == 8'h02;
  assign _102_ = { datain[6:0], rx } == 8'h03;
  assign _103_ = { datain[6:0], rx } == 8'h04;
  assign _104_ = { datain[6:0], rx } == 8'h05;
  assign _105_ = { datain[6:0], rx } == 8'h06;
  sync_bit_Brtl sync_cs_inst (
    .bit_i(cs_i),
    .bit_o(_085_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_rx_inst (
    .bit_i(rx_i),
    .bit_o(_086_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_sck_inst (
    .bit_i(sck_i),
    .bit_o(_084_),
    .clk_i(clk_i)
  );
  assign dataout = _072_;
  assign datain = _073_;
  assign sck_prev = _074_;
  assign sck_fall = _088_;
  assign sck_rise = _090_;
  assign sck = _084_;
  assign cs = _085_;
  assign rx = _086_;
  assign bit_counter = _075_;
  assign n_err = _076_;
  assign n_over = _077_;
  assign n_pos = _078_;
  assign new_pos = _079_;
  assign io_out = _080_;
  assign io_dir = _081_;
  assign io_in = _083_;
  assign tx_o = _061_;
  assign override_trig_o = _062_;
  assign ntrig_o = _063_;
  assign trig_period_o = _064_;
  assign width_o = _065_;
  assign pos_req_o = _066_;
  assign acq_start_o = _067_;
  assign bissc_half_clk_period_o = _068_;
  assign bissc_n_rising_edges_o = _069_;
  assign io_dir_o = _070_;
  assign io_out_o = _071_;
endmodule

module sync_bit_Brtl(clk_i, bit_i, bit_o);
  input clk_i;
  wire clk_i;
  input bit_i;
  wire bit_i;
  output bit_o;
  wire bit_o;
  reg _0_;
  reg _1_ = 1'h0;
  wire bit_meta;
  always @(posedge clk_i)
    _0_ <= bit_meta;
  always @(posedge clk_i)
    _1_ <= bit_i;
  assign bit_meta = _1_;
  assign bit_o = _0_;
endmodule

module trigger_generator_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, busy_o, trig_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire [31:0] _07_;
  wire _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire _11_;
  wire [31:0] _12_;
  wire [31:0] _13_;
  wire _14_;
  wire _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  wire _18_;
  wire _19_;
  wire [31:0] _20_;
  wire [31:0] _21_;
  wire _22_;
  reg _23_;
  reg _24_;
  reg [31:0] _25_;
  reg [31:0] _26_;
  reg _27_;
  wire running;
  wire [31:0] trig_count;
  wire [31:0] trig_timer;
  assign _00_ = running | go_i;
  assign _01_ = trig_timer == 32'd0;
  assign _02_ = trig_count == 32'd0;
  assign _03_ = trig_count - 32'd1;
  assign _04_ = _02_ ? trig_timer : trig_period_i;
  assign _05_ = _02_ ? trig_count : _03_;
  assign _06_ = _11_ ? 1'h0 : running;
  assign _07_ = trig_timer - 32'd1;
  assign _08_ = _01_ ? 1'h1 : 1'h0;
  assign _09_ = _01_ ? _04_ : _07_;
  assign _10_ = _01_ ? _05_ : trig_count;
  assign _11_ = _02_ & _01_;
  assign _12_ = go_i ? trig_period_i : trig_timer;
  assign _13_ = go_i ? ntrig_i : trig_count;
  assign _14_ = go_i ? 1'h1 : running;
  assign _15_ = running ? _08_ : 1'h0;
  assign _16_ = running ? _09_ : _12_;
  assign _17_ = running ? _10_ : _13_;
  assign _18_ = running ? _06_ : _14_;
  assign _19_ = rst_i ? 1'h0 : _15_;
  assign _20_ = rst_i ? 32'd0 : _16_;
  assign _21_ = rst_i ? 32'd0 : _17_;
  assign _22_ = rst_i ? 1'h0 : _18_;
  always @(posedge clk_i)
    _23_ <= _00_;
  always @(posedge clk_i)
    _24_ <= _19_;
  always @(posedge clk_i)
    _25_ <= _20_;
  always @(posedge clk_i)
    _26_ <= _21_;
  always @(posedge clk_i)
    _27_ <= _22_;
  assign trig_timer = _25_;
  assign trig_count = _26_;
  assign running = _27_;
  assign busy_o = _23_;
  assign trig_o = _24_;
endmodule

module tt_um_emiliopeju_lightscan(clk, ui_in, uio_in, ena, rst_n, uo_out, uio_out, uio_oe);
  input clk;
  wire clk;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  input ena;
  wire ena;
  input rst_n;
  wire rst_n;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [5:0] _03_;
  wire [5:0] _04_;
  wire [5:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [50:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [31:0] _18_;
  wire [31:0] _19_;
  wire [25:0] _20_;
  wire _21_;
  wire acq_start;
  wire biss_data_sync;
  wire bissc_go;
  wire [7:0] bissc_half_clk_period;
  wire [5:0] bissc_n_rising_edges;
  wire [31:0] ntrig;
  wire override_trig;
  wire [50:0] pos;
  wire pos_err;
  wire pos_req;
  wire pos_valid;
  wire rst;
  wire trig;
  wire trig_from_pulser;
  wire [31:0] trig_period;
  wire [25:0] width;
  assign _00_ = ~ rst_n;
  assign _11_ = pos_req | trig;
  assign _15_ = trig_from_pulser | override_trig;
  bissc_Barch bissc_inst (
    .clk_i(clk),
    .clk_o(_14_),
    .data_i(biss_data_sync),
    .err_o(_13_),
    .go_i(bissc_go),
    .half_clk_period_i(bissc_half_clk_period),
    .n_rising_edges_i(bissc_n_rising_edges),
    .pos_o(_10_),
    .rst_i(rst),
    .valid_o(_12_)
  );
  pulsed_trigger_Brtl pulsed_trigger_inst (
    .busy_o(_06_),
    .clk_i(clk),
    .go_i(acq_start),
    .ntrig_i(ntrig),
    .pulse_o(_08_),
    .rst_i(rst),
    .trig_o(_07_),
    .trig_period_i(trig_period),
    .width_i(width)
  );
  spi_registers_Brtl reg_inst (
    .acq_start_o(_01_),
    .bissc_half_clk_period_o(_02_),
    .bissc_n_rising_edges_o(_03_),
    .clk_i(clk),
    .cs_i(ui_in[0]),
    .error_event_i(pos_err),
    .io_dir_o(_04_),
    .io_in_i(uio_in[7:2]),
    .io_out_o(_05_),
    .ntrig_o(_18_),
    .override_trig_o(_17_),
    .pos_i(pos),
    .pos_req_o(_21_),
    .pos_valid_i(pos_valid),
    .rst_i(rst),
    .rx_i(ui_in[2]),
    .sck_i(ui_in[1]),
    .trig_i(trig),
    .trig_period_o(_19_),
    .tx_o(_16_),
    .width_o(_20_)
  );
  sync_bit_Brtl sync_biss_data_inst (
    .bit_i(uio_in[1]),
    .bit_o(_09_),
    .clk_i(clk)
  );
  assign pos = _10_;
  assign pos_valid = _12_;
  assign pos_err = _13_;
  assign pos_req = _21_;
  assign rst = _00_;
  assign biss_data_sync = _09_;
  assign bissc_go = _11_;
  assign acq_start = _01_;
  assign trig = _15_;
  assign trig_from_pulser = _07_;
  assign override_trig = _17_;
  assign trig_period = _19_;
  assign ntrig = _18_;
  assign width = _20_;
  assign bissc_half_clk_period = _02_;
  assign bissc_n_rising_edges = _03_;
  assign uo_out = { 4'hz, _16_, pos_valid, _08_, _06_ };
  assign uio_out = { _05_, 1'hz, _14_ };
  assign uio_oe = { _04_, 2'h1 };
endmodule
