/* Generated by Yosys 0.62 (git sha1 v0.62, g++ 15.2.0 -fPIC -O3) */

module bissc_Barch(clk_i, rst_i, go_i, half_clk_period_i, n_rising_edges_i, data_i, pos_o, valid_o, err_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input data_i;
  wire data_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  output clk_o;
  wire clk_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [50:0] _4_;
  wire _5_;
  wire _6_;
  wire clock_done;
  wire data;
  wire samp;
  bissc_capture_Brtl bissc_capture_inst (
    .clk_i(clk_i),
    .data_i(data),
    .done_i(clock_done),
    .err_o(_6_),
    .go_i(go_i),
    .pos_o(_4_),
    .rst_i(rst_i),
    .samp_i(samp),
    .valid_o(_5_)
  );
  bissc_extended_clock_Brtl bissc_extended_clock_inst (
    .clk_i(clk_i),
    .clk_o(_3_),
    .data_i(data_i),
    .data_o(_2_),
    .done_o(_0_),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i),
    .samp_o(_1_)
  );
  assign clock_done = _0_;
  assign data = _2_;
  assign samp = _1_;
  assign pos_o = _4_;
  assign valid_o = _5_;
  assign err_o = _6_;
  assign clk_o = _3_;
endmodule

module bissc_capture_Brtl(clk_i, rst_i, go_i, samp_i, data_i, done_i, pos_o, valid_o, err_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input samp_i;
  wire samp_i;
  input data_i;
  wire data_i;
  input done_i;
  wire done_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [2:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [5:0] _11_;
  wire [58:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [50:0] _17_;
  wire _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire [50:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  wire [2:0] _26_;
  wire [5:0] _27_;
  wire [58:0] _28_;
  wire [50:0] _29_;
  wire _30_;
  wire _31_;
  wire [1:0] _32_;
  wire [2:0] _33_;
  wire [5:0] _34_;
  wire [58:0] _35_;
  reg [50:0] _36_;
  reg _37_;
  reg _38_;
  reg [1:0] _39_ = 2'h0;
  reg [2:0] _40_;
  reg [5:0] _41_;
  reg [58:0] _42_;
  wire [5:0] crc;
  wire [2:0] initial_bits;
  wire [58:0] shift_pos;
  wire [1:0] state;
  assign _00_ = go_i ? 2'h1 : state;
  assign _01_ = state == 2'h0;
  assign _02_ = done_i ? 1'h1 : 1'h0;
  assign _03_ = done_i ? 2'h0 : state;
  assign _04_ = { initial_bits[1:0], data_i } == 3'h2;
  assign _05_ = _06_ ? 2'h2 : _03_;
  assign _06_ = _04_ & samp_i;
  assign _07_ = samp_i ? { initial_bits[1:0], data_i } : initial_bits;
  assign _08_ = state == 2'h1;
  assign _09_ = crc[0] ^ crc[5];
  assign _10_ = data_i ^ crc[5];
  assign _11_ = samp_i ? { crc[4:1], _09_, _10_ } : crc;
  assign _12_ = samp_i ? { shift_pos[57:0], data_i } : shift_pos;
  assign _13_ = crc != 6'h3f;
  assign _14_ = ~ shift_pos[7];
  assign _15_ = _13_ | _14_;
  assign _16_ = _15_ ? 1'h1 : 1'h0;
  assign _17_ = done_i ? shift_pos[58:8] : _36_;
  assign _18_ = done_i ? 1'h1 : 1'h0;
  assign _19_ = done_i ? _16_ : 1'h0;
  assign _20_ = done_i ? 2'h0 : state;
  assign _21_ = state == 2'h2;
  function [50:0] \:546 ;
    input [50:0] a;
    input [152:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:546  = b[50:0];
      3'b?1?:
        \:546  = b[101:51];
      3'b1??:
        \:546  = b[152:102];
      default:
        \:546  = a;
    endcase
  endfunction
  assign _22_ = \:546 (51'hxxxxxxxxxxxxx, { _17_, _36_, _36_ }, { _21_, _08_, _01_ });
  function [0:0] \:549 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:549  = b[0:0];
      3'b?1?:
        \:549  = b[1:1];
      3'b1??:
        \:549  = b[2:2];
      default:
        \:549  = a;
    endcase
  endfunction
  assign _23_ = \:549 (1'hx, { _18_, 2'h0 }, { _21_, _08_, _01_ });
  function [0:0] \:552 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:552  = b[0:0];
      3'b?1?:
        \:552  = b[1:1];
      3'b1??:
        \:552  = b[2:2];
      default:
        \:552  = a;
    endcase
  endfunction
  assign _24_ = \:552 (1'hx, { _19_, _02_, 1'h0 }, { _21_, _08_, _01_ });
  function [1:0] \:554 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:554  = b[1:0];
      3'b?1?:
        \:554  = b[3:2];
      3'b1??:
        \:554  = b[5:4];
      default:
        \:554  = a;
    endcase
  endfunction
  assign _25_ = \:554 (2'hx, { _20_, _05_, _00_ }, { _21_, _08_, _01_ });
  function [2:0] \:557 ;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:557  = b[2:0];
      3'b?1?:
        \:557  = b[5:3];
      3'b1??:
        \:557  = b[8:6];
      default:
        \:557  = a;
    endcase
  endfunction
  assign _26_ = \:557 (3'hx, { initial_bits, _07_, 3'h0 }, { _21_, _08_, _01_ });
  function [5:0] \:560 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:560  = b[5:0];
      3'b?1?:
        \:560  = b[11:6];
      3'b1??:
        \:560  = b[17:12];
      default:
        \:560  = a;
    endcase
  endfunction
  assign _27_ = \:560 (6'hxx, { _11_, crc, 6'h00 }, { _21_, _08_, _01_ });
  function [58:0] \:563 ;
    input [58:0] a;
    input [176:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:563  = b[58:0];
      3'b?1?:
        \:563  = b[117:59];
      3'b1??:
        \:563  = b[176:118];
      default:
        \:563  = a;
    endcase
  endfunction
  assign _28_ = \:563 (59'hxxxxxxxxxxxxxxx, { _12_, shift_pos, 59'h000000000000000 }, { _21_, _08_, _01_ });
  assign _29_ = rst_i ? _36_ : _22_;
  assign _30_ = rst_i ? 1'h0 : _23_;
  assign _31_ = rst_i ? 1'h0 : _24_;
  assign _32_ = rst_i ? 2'h0 : _25_;
  assign _33_ = rst_i ? initial_bits : _26_;
  assign _34_ = rst_i ? crc : _27_;
  assign _35_ = rst_i ? shift_pos : _28_;
  always @(posedge clk_i)
    _36_ <= _29_;
  always @(posedge clk_i)
    _37_ <= _30_;
  always @(posedge clk_i)
    _38_ <= _31_;
  always @(posedge clk_i)
    _39_ <= _32_;
  always @(posedge clk_i)
    _40_ <= _33_;
  always @(posedge clk_i)
    _41_ <= _34_;
  always @(posedge clk_i)
    _42_ <= _35_;
  assign state = _39_;
  assign initial_bits = _40_;
  assign crc = _41_;
  assign shift_pos = _42_;
  assign pos_o = _36_;
  assign valid_o = _37_;
  assign err_o = _38_;
endmodule

module bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire _09_;
  wire [1:0] _10_;
  wire [5:0] _11_;
  wire _12_;
  wire _13_;
  wire [5:0] _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire [7:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [1:0] _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire [7:0] _28_;
  wire [1:0] _29_;
  wire [5:0] _30_;
  wire _31_;
  wire _32_;
  wire [7:0] _33_;
  wire [1:0] _34_;
  wire [5:0] _35_;
  reg _36_;
  reg _37_;
  reg [7:0] _38_;
  reg [1:0] _39_;
  reg [5:0] _40_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _36_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _37_;
  assign _06_ = ~ _37_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 1'h0 : _36_;
  assign _10_ = _19_ ? 2'h0 : clock_state;
  assign _11_ = _07_ ? rising_counter : _08_;
  assign _12_ = _07_ & _06_;
  assign _13_ = _07_ & _06_;
  assign _14_ = _20_ ? _11_ : rising_counter;
  assign _15_ = clock_timer - 8'h01;
  assign _16_ = _12_ & _04_;
  assign _17_ = _04_ ? _05_ : _37_;
  assign _18_ = _04_ ? half_clk_period_i : _15_;
  assign _19_ = _13_ & _04_;
  assign _20_ = _06_ & _04_;
  assign _21_ = clock_state == 2'h1;
  assign _22_ = data_i | go_i;
  assign _23_ = _22_ ? 1'h0 : _36_;
  assign _24_ = _22_ ? 2'h0 : clock_state;
  assign _25_ = clock_state == 2'h2;
  function [0:0] \:706 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:706  = b[0:0];
      3'b?1?:
        \:706  = b[1:1];
      3'b1??:
        \:706  = b[2:2];
      default:
        \:706  = a;
    endcase
  endfunction
  assign _26_ = \:706 (_36_, { _23_, _09_, _00_ }, { _25_, _21_, _03_ });
  function [0:0] \:707 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:707  = b[0:0];
      3'b?1?:
        \:707  = b[1:1];
      3'b1??:
        \:707  = b[2:2];
      default:
        \:707  = a;
    endcase
  endfunction
  assign _27_ = \:707 (_37_, { _37_, _17_, _01_ }, { _25_, _21_, _03_ });
  function [7:0] \:708 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:708  = b[7:0];
      3'b?1?:
        \:708  = b[15:8];
      3'b1??:
        \:708  = b[23:16];
      default:
        \:708  = a;
    endcase
  endfunction
  assign _28_ = \:708 (clock_timer, { clock_timer, _18_, half_clk_period_i }, { _25_, _21_, _03_ });
  function [1:0] \:709 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:709  = b[1:0];
      3'b?1?:
        \:709  = b[3:2];
      3'b1??:
        \:709  = b[5:4];
      default:
        \:709  = a;
    endcase
  endfunction
  assign _29_ = \:709 (clock_state, { _24_, _10_, _02_ }, { _25_, _21_, _03_ });
  function [5:0] \:710 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:710  = b[5:0];
      3'b?1?:
        \:710  = b[11:6];
      3'b1??:
        \:710  = b[17:12];
      default:
        \:710  = a;
    endcase
  endfunction
  assign _30_ = \:710 (rising_counter, { rising_counter, _14_, n_rising_edges_i }, { _25_, _21_, _03_ });
  assign _31_ = rst_i ? 1'h0 : _26_;
  assign _32_ = rst_i ? _37_ : _27_;
  assign _33_ = rst_i ? clock_timer : _28_;
  assign _34_ = rst_i ? 2'h0 : _29_;
  assign _35_ = rst_i ? rising_counter : _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  always @(posedge clk_i)
    _38_ <= _33_;
  always @(posedge clk_i)
    _39_ <= _34_;
  always @(posedge clk_i)
    _40_ <= _35_;
  assign clock_timer = _38_;
  assign clock_state = _39_;
  assign rising_counter = _40_;
  assign busy_o = _36_;
  assign clk_o = _37_;
endmodule

module bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire [1:0] _09_;
  wire [5:0] _10_;
  wire _11_;
  wire [5:0] _12_;
  wire [7:0] _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire [1:0] _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [7:0] _25_;
  wire [1:0] _26_;
  wire [5:0] _27_;
  wire _28_;
  wire _29_;
  wire [7:0] _30_;
  wire [1:0] _31_;
  wire [5:0] _32_;
  reg _33_;
  reg _34_;
  reg [7:0] _35_;
  reg [1:0] _36_;
  reg [5:0] _37_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _33_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _34_;
  assign _06_ = ~ _34_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 2'h2 : clock_state;
  assign _10_ = _07_ ? rising_counter : _08_;
  assign _11_ = _07_ & _06_;
  assign _12_ = _17_ ? _10_ : rising_counter;
  assign _13_ = clock_timer - 8'h01;
  assign _14_ = _04_ ? _05_ : _34_;
  assign _15_ = _04_ ? half_clk_period_i : _13_;
  assign _16_ = _11_ & _04_;
  assign _17_ = _06_ & _04_;
  assign _18_ = clock_state == 2'h1;
  assign _19_ = data_i | go_i;
  assign _20_ = _19_ ? 1'h0 : _33_;
  assign _21_ = _19_ ? 2'h0 : clock_state;
  assign _22_ = clock_state == 2'h2;
  function [0:0] \:637 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:637  = b[0:0];
      3'b?1?:
        \:637  = b[1:1];
      3'b1??:
        \:637  = b[2:2];
      default:
        \:637  = a;
    endcase
  endfunction
  assign _23_ = \:637 (_33_, { _20_, _33_, _00_ }, { _22_, _18_, _03_ });
  function [0:0] \:638 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:638  = b[0:0];
      3'b?1?:
        \:638  = b[1:1];
      3'b1??:
        \:638  = b[2:2];
      default:
        \:638  = a;
    endcase
  endfunction
  assign _24_ = \:638 (_34_, { _34_, _14_, _01_ }, { _22_, _18_, _03_ });
  function [7:0] \:639 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:639  = b[7:0];
      3'b?1?:
        \:639  = b[15:8];
      3'b1??:
        \:639  = b[23:16];
      default:
        \:639  = a;
    endcase
  endfunction
  assign _25_ = \:639 (clock_timer, { clock_timer, _15_, half_clk_period_i }, { _22_, _18_, _03_ });
  function [1:0] \:640 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:640  = b[1:0];
      3'b?1?:
        \:640  = b[3:2];
      3'b1??:
        \:640  = b[5:4];
      default:
        \:640  = a;
    endcase
  endfunction
  assign _26_ = \:640 (clock_state, { _21_, _09_, _02_ }, { _22_, _18_, _03_ });
  function [5:0] \:641 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:641  = b[5:0];
      3'b?1?:
        \:641  = b[11:6];
      3'b1??:
        \:641  = b[17:12];
      default:
        \:641  = a;
    endcase
  endfunction
  assign _27_ = \:641 (rising_counter, { rising_counter, _12_, n_rising_edges_i }, { _22_, _18_, _03_ });
  assign _28_ = rst_i ? 1'h0 : _23_;
  assign _29_ = rst_i ? _34_ : _24_;
  assign _30_ = rst_i ? clock_timer : _25_;
  assign _31_ = rst_i ? 2'h0 : _26_;
  assign _32_ = rst_i ? rising_counter : _27_;
  always @(posedge clk_i)
    _33_ <= _28_;
  always @(posedge clk_i)
    _34_ <= _29_;
  always @(posedge clk_i)
    _35_ <= _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  assign clock_timer = _35_;
  assign clock_state = _36_;
  assign rising_counter = _37_;
  assign busy_o = _33_;
  assign clk_o = _34_;
endmodule

module bissc_extended_clock_Brtl(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, done_o, samp_o, data_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output done_o;
  wire done_o;
  output samp_o;
  wire samp_o;
  output data_o;
  wire data_o;
  output clk_o;
  wire clk_o;
  wire [5:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [1:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [1:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [1:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  reg _26_;
  reg _27_;
  reg _28_;
  reg [1:0] _29_ = 2'h0;
  reg _30_;
  reg _31_;
  wire busy1;
  wire busy2;
  wire data_dly;
  wire data_dly2;
  wire go2;
  wire [5:0] nbits;
  wire samp_clk;
  wire samp_clk_dly;
  wire samp_clk_rise;
  wire [1:0] state;
  assign _00_ = n_rising_edges_i - 6'h02;
  assign _05_ = ~ samp_clk_dly;
  assign _06_ = samp_clk & _05_;
  assign _07_ = go_i ? 2'h1 : state;
  assign _08_ = state == 2'h0;
  assign _09_ = ~ data_i;
  assign _10_ = go_i ? 2'h2 : state;
  assign _11_ = _09_ ? 1'h1 : 1'h0;
  assign _12_ = _09_ ? 2'h2 : _10_;
  assign _13_ = state == 2'h1;
  assign _14_ = ~ busy1;
  assign _15_ = ~ busy2;
  assign _16_ = _14_ & _15_;
  assign _17_ = _16_ ? 1'h1 : 1'h0;
  assign _18_ = _16_ ? 2'h0 : state;
  assign _19_ = state == 2'h2;
  function [0:0] \:462 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:462  = b[0:0];
      3'b?1?:
        \:462  = b[1:1];
      3'b1??:
        \:462  = b[2:2];
      default:
        \:462  = a;
    endcase
  endfunction
  assign _20_ = \:462 (1'h0, { _17_, 2'h0 }, { _19_, _13_, _08_ });
  function [0:0] \:465 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:465  = b[0:0];
      3'b?1?:
        \:465  = b[1:1];
      3'b1??:
        \:465  = b[2:2];
      default:
        \:465  = a;
    endcase
  endfunction
  assign _21_ = \:465 (1'h0, { 1'h0, _11_, 1'h0 }, { _19_, _13_, _08_ });
  function [1:0] \:466 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:466  = b[1:0];
      3'b?1?:
        \:466  = b[3:2];
      3'b1??:
        \:466  = b[5:4];
      default:
        \:466  = a;
    endcase
  endfunction
  assign _22_ = \:466 (state, { _18_, _12_, _07_ }, { _19_, _13_, _08_ });
  assign _23_ = rst_i ? _26_ : _20_;
  assign _24_ = rst_i ? 1'h0 : _21_;
  assign _25_ = rst_i ? 2'h0 : _22_;
  always @(posedge clk_i)
    _26_ <= _23_;
  always @(posedge clk_i)
    _27_ <= samp_clk;
  always @(posedge clk_i)
    _28_ <= _24_;
  always @(posedge clk_i)
    _29_ <= _25_;
  always @(posedge clk_i)
    _30_ <= data_i;
  always @(posedge clk_i)
    _31_ <= data_dly;
  bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e bissc_clock_inst (
    .busy_o(_01_),
    .clk_i(clk_i),
    .clk_o(_02_),
    .data_i(data_i),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i)
  );
  bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9 bissc_samp_clock_inst (
    .busy_o(_03_),
    .clk_i(clk_i),
    .clk_o(_04_),
    .data_i(data_i),
    .go_i(go2),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(nbits),
    .rst_i(rst_i)
  );
  assign nbits = _00_;
  assign samp_clk = _04_;
  assign samp_clk_dly = _27_;
  assign samp_clk_rise = _06_;
  assign go2 = _28_;
  assign state = _29_;
  assign data_dly = _30_;
  assign data_dly2 = _31_;
  assign busy1 = _01_;
  assign busy2 = _03_;
  assign done_o = _26_;
  assign samp_o = samp_clk_rise;
  assign data_o = data_dly2;
  assign clk_o = _02_;
endmodule

module deglitcher_Brtl_3(clk_i, bit_i, bit_o);
  input clk_i;
  wire clk_i;
  input bit_i;
  wire bit_i;
  output bit_o;
  wire bit_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  reg _4_;
  reg [2:0] _5_;
  wire [2:0] bit_shift;
  assign _0_ = bit_shift == 3'h7;
  assign _1_ = bit_shift == 3'h0;
  assign _2_ = _1_ ? 1'h0 : _4_;
  assign _3_ = _0_ ? 1'h1 : _2_;
  always @(posedge clk_i)
    _4_ <= _3_;
  always @(posedge clk_i)
    _5_ <= { bit_shift[1:0], bit_i };
  assign bit_shift = _5_;
  assign bit_o = _4_;
endmodule

module pulse_stretch_Brtl(clk_i, rst_i, width_i, trig_i, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  input trig_i;
  wire trig_i;
  output pulse_o;
  wire pulse_o;
  wire _00_;
  wire _01_;
  wire [25:0] _02_;
  wire [25:0] _03_;
  wire _04_;
  wire [25:0] _05_;
  wire _06_;
  wire [25:0] _07_;
  wire _08_;
  reg [25:0] _09_;
  reg _10_;
  wire pulse;
  wire [25:0] pulse_timer;
  assign _00_ = pulse | trig_i;
  assign _01_ = pulse_timer != 26'h0000000;
  assign _02_ = pulse_timer - 26'h0000001;
  assign _03_ = _01_ ? _02_ : pulse_timer;
  assign _04_ = _01_ ? 1'h1 : 1'h0;
  assign _05_ = trig_i ? width_i : _03_;
  assign _06_ = trig_i ? 1'h1 : _04_;
  assign _07_ = rst_i ? 26'h0000000 : _05_;
  assign _08_ = rst_i ? 1'h0 : _06_;
  always @(posedge clk_i)
    _09_ <= _07_;
  always @(posedge clk_i)
    _10_ <= _08_;
  assign pulse_timer = _09_;
  assign pulse = _10_;
  assign pulse_o = _00_;
endmodule

module pulsed_trigger_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, width_i, busy_o, trig_o, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  output pulse_o;
  wire pulse_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire busy;
  wire trig;
  assign _0_ = busy | _1_;
  pulse_stretch_Brtl pulse_stretch_inst (
    .clk_i(clk_i),
    .pulse_o(_1_),
    .rst_i(rst_i),
    .trig_i(trig),
    .width_i(width_i)
  );
  trigger_generator_Brtl trig_gen_inst (
    .busy_o(_2_),
    .clk_i(clk_i),
    .go_i(go_i),
    .ntrig_i(ntrig_i),
    .rst_i(rst_i),
    .trig_o(_3_),
    .trig_period_i(trig_period_i)
  );
  assign trig = _3_;
  assign busy = _2_;
  assign busy_o = _0_;
  assign trig_o = trig;
  assign pulse_o = _1_;
endmodule

module spi_registers_Brtl(clk_i, rst_i, cs_i, sck_i, rx_i, pos_i, pos_valid_i, error_event_i, tx_o, ntrig_o, trig_period_o, width_o, pos_req_o, acq_start_o, bissc_half_clk_period_o, bissc_n_rising_edges_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input cs_i;
  wire cs_i;
  input sck_i;
  wire sck_i;
  input rx_i;
  wire rx_i;
  input [31:0] pos_i;
  wire [31:0] pos_i;
  input pos_valid_i;
  wire pos_valid_i;
  input error_event_i;
  wire error_event_i;
  output tx_o;
  wire tx_o;
  output [31:0] ntrig_o;
  wire [31:0] ntrig_o;
  output [31:0] trig_period_o;
  wire [31:0] trig_period_o;
  output [25:0] width_o;
  wire [25:0] width_o;
  output pos_req_o;
  wire pos_req_o;
  output acq_start_o;
  wire acq_start_o;
  output [7:0] bissc_half_clk_period_o;
  wire [7:0] bissc_half_clk_period_o;
  output [5:0] bissc_n_rising_edges_o;
  wire [5:0] bissc_n_rising_edges_o;
  wire _000_;
  wire [7:0] _001_;
  wire [5:0] _002_;
  wire [31:0] _003_;
  wire [39:0] _004_;
  wire [5:0] _005_;
  wire _006_;
  wire _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [25:0] _010_;
  wire _011_;
  wire _012_;
  wire [7:0] _013_;
  wire [5:0] _014_;
  wire [31:0] _015_;
  wire [39:0] _016_;
  wire [5:0] _017_;
  wire [7:0] _018_;
  wire _019_;
  wire [7:0] _020_;
  wire [7:0] _021_;
  wire _022_;
  wire _023_;
  reg _024_;
  reg [31:0] _025_;
  reg [31:0] _026_;
  reg [25:0] _027_;
  reg _028_;
  reg _029_;
  reg [7:0] _030_;
  reg [5:0] _031_;
  reg [31:0] _032_;
  reg [39:0] _033_;
  reg _034_;
  reg _035_;
  reg [5:0] _036_;
  reg [7:0] _037_;
  reg [7:0] _038_;
  reg [15:0] _039_;
  reg _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire [15:0] _050_;
  wire [15:0] _051_;
  wire [7:0] _052_;
  wire [7:0] _053_;
  wire [7:0] _054_;
  wire [15:0] _055_;
  wire [5:0] _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire [5:0] _066_;
  wire [1:0] _067_;
  wire [17:0] _068_;
  wire [5:0] _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [31:0] _079_;
  wire [31:0] _080_;
  wire [25:0] _081_;
  wire _082_;
  wire _083_;
  wire [7:0] _084_;
  wire [5:0] _085_;
  wire [31:0] _086_;
  wire [31:0] _087_;
  wire [25:0] _088_;
  wire _089_;
  wire _090_;
  wire [7:0] _091_;
  wire [5:0] _092_;
  wire [31:0] _093_;
  wire [31:0] _094_;
  wire [25:0] _095_;
  wire _096_;
  wire _097_;
  wire [7:0] _098_;
  wire [5:0] _099_;
  wire [31:0] _100_;
  wire _101_;
  wire _102_;
  wire [31:0] _103_;
  wire _104_;
  wire [31:0] _105_;
  wire [31:0] _106_;
  wire [25:0] _107_;
  wire _108_;
  wire _109_;
  wire [7:0] _110_;
  wire [5:0] _111_;
  wire [31:0] _112_;
  wire [39:0] _113_;
  wire [5:0] _114_;
  wire _115_;
  wire _116_;
  wire [31:0] _117_;
  wire [31:0] _118_;
  wire [25:0] _119_;
  wire _120_;
  wire [5:0] bit_counter;
  wire cs;
  wire cs_fall;
  wire cs_prev;
  wire [39:0] datain;
  wire [31:0] dataout;
  wire [7:0] n_err;
  wire [7:0] n_over;
  wire [15:0] n_pos;
  wire new_pos;
  wire rx;
  wire sck;
  wire sck_fall;
  wire sck_prev;
  wire sck_rise;
  function [5:0] \:106 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:106  = b[5:0];
      8'b??????1?:
        \:106  = b[11:6];
      8'b?????1??:
        \:106  = b[17:12];
      8'b????1???:
        \:106  = b[23:18];
      8'b???1????:
        \:106  = b[29:24];
      8'b??1?????:
        \:106  = b[35:30];
      8'b?1??????:
        \:106  = b[41:36];
      8'b1???????:
        \:106  = b[47:42];
      default:
        \:106  = a;
    endcase
  endfunction
  assign _066_ = \:106 (6'h00, { _031_, _030_[5:0], _027_[5:0], _025_[5:0], _026_[5:0], pos_i[5:0], n_pos[5:0], 6'h01 }, { _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_ });
  function [1:0] \:116 ;
    input [1:0] a;
    input [15:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:116  = b[1:0];
      8'b??????1?:
        \:116  = b[3:2];
      8'b?????1??:
        \:116  = b[5:4];
      8'b????1???:
        \:116  = b[7:6];
      8'b???1????:
        \:116  = b[9:8];
      8'b??1?????:
        \:116  = b[11:10];
      8'b?1??????:
        \:116  = b[13:12];
      8'b1???????:
        \:116  = b[15:14];
      default:
        \:116  = a;
    endcase
  endfunction
  assign _067_ = \:116 (2'h0, { 2'h0, _030_[7:6], _027_[7:6], _025_[7:6], _026_[7:6], pos_i[7:6], n_pos[7:6], 2'h0 }, { _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_ });
  function [17:0] \:126 ;
    input [17:0] a;
    input [143:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:126  = b[17:0];
      8'b??????1?:
        \:126  = b[35:18];
      8'b?????1??:
        \:126  = b[53:36];
      8'b????1???:
        \:126  = b[71:54];
      8'b???1????:
        \:126  = b[89:72];
      8'b??1?????:
        \:126  = b[107:90];
      8'b?1??????:
        \:126  = b[125:108];
      8'b1???????:
        \:126  = b[143:126];
      default:
        \:126  = a;
    endcase
  endfunction
  assign _068_ = \:126 (18'h00000, { 36'h000000000, _027_[25:8], _025_[25:8], _026_[25:8], pos_i[25:8], n_over[1:0], n_err, n_pos[15:8], 18'h00000 }, { _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_ });
  function [5:0] \:135 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:135  = b[5:0];
      8'b??????1?:
        \:135  = b[11:6];
      8'b?????1??:
        \:135  = b[17:12];
      8'b????1???:
        \:135  = b[23:18];
      8'b???1????:
        \:135  = b[29:24];
      8'b??1?????:
        \:135  = b[35:30];
      8'b?1??????:
        \:135  = b[41:36];
      8'b1???????:
        \:135  = b[47:42];
      default:
        \:135  = a;
    endcase
  endfunction
  assign _069_ = \:135 (6'h00, { 18'h00000, _025_[31:26], _026_[31:26], pos_i[31:26], n_over[7:2], 6'h20 }, { _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_ });
  function [0:0] \:137 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:137  = b[0:0];
      8'b??????1?:
        \:137  = b[1:1];
      8'b?????1??:
        \:137  = b[2:2];
      8'b????1???:
        \:137  = b[3:3];
      8'b???1????:
        \:137  = b[4:4];
      8'b??1?????:
        \:137  = b[5:5];
      8'b?1??????:
        \:137  = b[6:6];
      8'b1???????:
        \:137  = b[7:7];
      default:
        \:137  = a;
    endcase
  endfunction
  assign _070_ = \:137 (new_pos, { new_pos, new_pos, new_pos, new_pos, new_pos, 1'h0, new_pos, new_pos }, { _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_ });
  assign _071_ = bit_counter == 6'h27;
  assign _072_ = datain[38:31] == 8'h83;
  assign _073_ = datain[38:31] == 8'h84;
  assign _074_ = datain[38:31] == 8'h85;
  assign _075_ = datain[38:31] == 8'h86;
  assign _076_ = datain[38:31] == 8'h87;
  assign _077_ = datain[38:31] == 8'h88;
  assign _078_ = datain[38:31] == 8'h89;
  function [31:0] \:161 ;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:161  = b[31:0];
      7'b?????1?:
        \:161  = b[63:32];
      7'b????1??:
        \:161  = b[95:64];
      7'b???1???:
        \:161  = b[127:96];
      7'b??1????:
        \:161  = b[159:128];
      7'b?1?????:
        \:161  = b[191:160];
      7'b1??????:
        \:161  = b[223:192];
      default:
        \:161  = a;
    endcase
  endfunction
  assign _079_ = \:161 (_025_, { _025_, _025_, _025_, _025_, _025_, datain[30:0], rx, _025_ }, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [31:0] \:162 ;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:162  = b[31:0];
      7'b?????1?:
        \:162  = b[63:32];
      7'b????1??:
        \:162  = b[95:64];
      7'b???1???:
        \:162  = b[127:96];
      7'b??1????:
        \:162  = b[159:128];
      7'b?1?????:
        \:162  = b[191:160];
      7'b1??????:
        \:162  = b[223:192];
      default:
        \:162  = a;
    endcase
  endfunction
  assign _080_ = \:162 (_026_, { _026_, _026_, _026_, _026_, _026_, _026_, datain[30:0], rx }, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [25:0] \:163 ;
    input [25:0] a;
    input [181:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:163  = b[25:0];
      7'b?????1?:
        \:163  = b[51:26];
      7'b????1??:
        \:163  = b[77:52];
      7'b???1???:
        \:163  = b[103:78];
      7'b??1????:
        \:163  = b[129:104];
      7'b?1?????:
        \:163  = b[155:130];
      7'b1??????:
        \:163  = b[181:156];
      default:
        \:163  = a;
    endcase
  endfunction
  assign _081_ = \:163 (_027_, { _027_, _027_, _027_, _027_, datain[24:0], rx, _027_, _027_ }, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [0:0] \:166 ;
    input [0:0] a;
    input [6:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:166  = b[0:0];
      7'b?????1?:
        \:166  = b[1:1];
      7'b????1??:
        \:166  = b[2:2];
      7'b???1???:
        \:166  = b[3:3];
      7'b??1????:
        \:166  = b[4:4];
      7'b?1?????:
        \:166  = b[5:5];
      7'b1??????:
        \:166  = b[6:6];
      default:
        \:166  = a;
    endcase
  endfunction
  assign _082_ = \:166 (1'h0, 7'h20, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [0:0] \:169 ;
    input [0:0] a;
    input [6:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:169  = b[0:0];
      7'b?????1?:
        \:169  = b[1:1];
      7'b????1??:
        \:169  = b[2:2];
      7'b???1???:
        \:169  = b[3:3];
      7'b??1????:
        \:169  = b[4:4];
      7'b?1?????:
        \:169  = b[5:5];
      7'b1??????:
        \:169  = b[6:6];
      default:
        \:169  = a;
    endcase
  endfunction
  assign _083_ = \:169 (1'h0, 7'h40, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [7:0] \:170 ;
    input [7:0] a;
    input [55:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:170  = b[7:0];
      7'b?????1?:
        \:170  = b[15:8];
      7'b????1??:
        \:170  = b[23:16];
      7'b???1???:
        \:170  = b[31:24];
      7'b??1????:
        \:170  = b[39:32];
      7'b?1?????:
        \:170  = b[47:40];
      7'b1??????:
        \:170  = b[55:48];
      default:
        \:170  = a;
    endcase
  endfunction
  assign _084_ = \:170 (_030_, { _030_, _030_, _030_, datain[6:0], rx, _030_, _030_, _030_ }, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  function [5:0] \:171 ;
    input [5:0] a;
    input [41:0] b;
    input [6:0] s;
    (* parallel_case *)
    casez (s)
      7'b??????1:
        \:171  = b[5:0];
      7'b?????1?:
        \:171  = b[11:6];
      7'b????1??:
        \:171  = b[17:12];
      7'b???1???:
        \:171  = b[23:18];
      7'b??1????:
        \:171  = b[29:24];
      7'b?1?????:
        \:171  = b[35:30];
      7'b1??????:
        \:171  = b[41:36];
      default:
        \:171  = a;
    endcase
  endfunction
  assign _085_ = \:171 (_031_, { _031_, _031_, datain[4:0], rx, _031_, _031_, _031_, _031_ }, { _078_, _077_, _076_, _075_, _074_, _073_, _072_ });
  assign _086_ = _071_ ? _079_ : _025_;
  assign _087_ = _071_ ? _080_ : _026_;
  assign _088_ = _071_ ? _081_ : _027_;
  assign _089_ = _071_ ? _082_ : 1'h0;
  assign _090_ = _071_ ? _083_ : 1'h0;
  assign _091_ = _071_ ? _084_ : _030_;
  assign _092_ = _071_ ? _085_ : _031_;
  assign _093_ = _057_ ? _025_ : _086_;
  assign _094_ = _057_ ? _026_ : _087_;
  assign _095_ = _057_ ? _027_ : _088_;
  assign _096_ = _057_ ? 1'h0 : _089_;
  assign _097_ = _057_ ? 1'h0 : _090_;
  assign _098_ = _057_ ? _030_ : _091_;
  assign _099_ = _057_ ? _031_ : _092_;
  assign _100_ = _057_ ? { _069_, _068_, _067_, _066_ } : dataout;
  assign _101_ = _115_ ? _070_ : new_pos;
  assign _102_ = sck_fall ? dataout[31] : _024_;
  assign _103_ = sck_fall ? { dataout[30:0], 1'h0 } : dataout;
  assign _104_ = sck_rise ? _024_ : _102_;
  assign _105_ = sck_rise ? _093_ : _025_;
  assign _106_ = sck_rise ? _094_ : _026_;
  assign _107_ = sck_rise ? _095_ : _027_;
  assign _108_ = sck_rise ? _096_ : 1'h0;
  assign _109_ = sck_rise ? _097_ : 1'h0;
  assign _110_ = sck_rise ? _098_ : _030_;
  assign _111_ = sck_rise ? _099_ : _031_;
  assign _112_ = sck_rise ? _100_ : _103_;
  assign _113_ = sck_rise ? { datain[38:0], rx } : datain;
  assign _114_ = sck_rise ? _056_ : bit_counter;
  assign _115_ = _057_ & sck_rise;
  assign _116_ = cs_fall ? _024_ : _104_;
  assign _117_ = cs_fall ? _025_ : _105_;
  assign _118_ = cs_fall ? _026_ : _106_;
  assign _119_ = cs_fall ? _027_ : _107_;
  assign _120_ = cs_fall ? 1'h0 : _108_;
  assign _000_ = cs_fall ? 1'h0 : _109_;
  assign _001_ = cs_fall ? _030_ : _110_;
  assign _002_ = cs_fall ? _031_ : _111_;
  assign _003_ = cs_fall ? dataout : _112_;
  assign _004_ = cs_fall ? datain : _113_;
  assign _005_ = cs_fall ? 6'h00 : _114_;
  assign _006_ = cs_fall ? new_pos : _101_;
  assign _007_ = rst_i ? _024_ : _116_;
  assign _008_ = rst_i ? 32'd0 : _117_;
  assign _009_ = rst_i ? 32'd0 : _118_;
  assign _010_ = rst_i ? 26'h0000000 : _119_;
  assign _011_ = rst_i ? 1'h0 : _120_;
  assign _012_ = rst_i ? 1'h0 : _000_;
  assign _013_ = rst_i ? 8'h00 : _001_;
  assign _014_ = rst_i ? 6'h00 : _002_;
  assign _015_ = rst_i ? 32'd0 : _003_;
  assign _016_ = rst_i ? datain : _004_;
  assign _017_ = rst_i ? bit_counter : _005_;
  assign _018_ = rst_i ? 8'h00 : n_over;
  assign _019_ = rst_i ? 1'h0 : _006_;
  assign _020_ = n_over + 8'h01;
  assign _021_ = _022_ ? _020_ : _018_;
  assign _022_ = new_pos & pos_valid_i;
  assign _023_ = pos_valid_i ? 1'h1 : _019_;
  always @(posedge clk_i)
    _024_ <= _007_;
  always @(posedge clk_i)
    _025_ <= _008_;
  always @(posedge clk_i)
    _026_ <= _009_;
  always @(posedge clk_i)
    _027_ <= _010_;
  always @(posedge clk_i)
    _028_ <= _011_;
  always @(posedge clk_i)
    _029_ <= _012_;
  always @(posedge clk_i)
    _030_ <= _013_;
  always @(posedge clk_i)
    _031_ <= _014_;
  always @(posedge clk_i)
    _032_ <= _015_;
  always @(posedge clk_i)
    _033_ <= _016_;
  always @(posedge clk_i)
    _034_ <= cs;
  always @(posedge clk_i)
    _035_ <= sck;
  always @(posedge clk_i)
    _036_ <= _017_;
  always @(posedge clk_i)
    _037_ <= _054_;
  always @(posedge clk_i)
    _038_ <= _021_;
  always @(posedge clk_i)
    _039_ <= _055_;
  always @(posedge clk_i)
    _040_ <= _023_;
  assign _044_ = ~ cs;
  assign _045_ = cs_prev & _044_;
  assign _046_ = ~ sck;
  assign _047_ = sck_prev & _046_;
  assign _048_ = ~ sck_prev;
  assign _049_ = _048_ & sck;
  assign _050_ = n_pos + 16'h0001;
  assign _051_ = pos_valid_i ? _050_ : n_pos;
  assign _052_ = n_err + 8'h01;
  assign _053_ = error_event_i ? _052_ : n_err;
  assign _054_ = rst_i ? 8'h00 : _053_;
  assign _055_ = rst_i ? 16'h0000 : _051_;
  assign _056_ = bit_counter + 6'h01;
  assign _057_ = bit_counter == 6'h07;
  assign _058_ = { datain[6:0], rx } == 8'h00;
  assign _059_ = { datain[6:0], rx } == 8'h01;
  assign _060_ = { datain[6:0], rx } == 8'h02;
  assign _061_ = { datain[6:0], rx } == 8'h03;
  assign _062_ = { datain[6:0], rx } == 8'h04;
  assign _063_ = { datain[6:0], rx } == 8'h05;
  assign _064_ = { datain[6:0], rx } == 8'h06;
  assign _065_ = { datain[6:0], rx } == 8'h07;
  sync_bit_Brtl sync_cs_inst (
    .bit_i(cs_i),
    .bit_o(_042_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_rx_inst (
    .bit_i(rx_i),
    .bit_o(_043_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_sck_inst (
    .bit_i(sck_i),
    .bit_o(_041_),
    .clk_i(clk_i)
  );
  assign dataout = _032_;
  assign datain = _033_;
  assign cs_prev = _034_;
  assign cs_fall = _045_;
  assign sck_prev = _035_;
  assign sck_fall = _047_;
  assign sck_rise = _049_;
  assign sck = _041_;
  assign cs = _042_;
  assign rx = _043_;
  assign bit_counter = _036_;
  assign n_err = _037_;
  assign n_over = _038_;
  assign n_pos = _039_;
  assign new_pos = _040_;
  assign tx_o = _024_;
  assign ntrig_o = _025_;
  assign trig_period_o = _026_;
  assign width_o = _027_;
  assign pos_req_o = _028_;
  assign acq_start_o = _029_;
  assign bissc_half_clk_period_o = _030_;
  assign bissc_n_rising_edges_o = _031_;
endmodule

module sync_bit_Brtl(clk_i, bit_i, bit_o);
  input clk_i;
  wire clk_i;
  input bit_i;
  wire bit_i;
  output bit_o;
  wire bit_o;
  reg _0_;
  reg _1_ = 1'h0;
  wire bit_meta;
  always @(posedge clk_i)
    _0_ <= bit_meta;
  always @(posedge clk_i)
    _1_ <= bit_i;
  assign bit_meta = _1_;
  assign bit_o = _0_;
endmodule

module trigger_generator_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, busy_o, trig_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire [31:0] _07_;
  wire _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire _11_;
  wire [31:0] _12_;
  wire [31:0] _13_;
  wire _14_;
  wire _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  wire _18_;
  wire _19_;
  wire [31:0] _20_;
  wire [31:0] _21_;
  wire _22_;
  reg _23_;
  reg _24_;
  reg [31:0] _25_;
  reg [31:0] _26_;
  reg _27_;
  wire running;
  wire [31:0] trig_count;
  wire [31:0] trig_timer;
  assign _00_ = running | go_i;
  assign _01_ = trig_timer == 32'd0;
  assign _02_ = trig_count == 32'd0;
  assign _03_ = trig_count - 32'd1;
  assign _04_ = _02_ ? trig_timer : trig_period_i;
  assign _05_ = _02_ ? trig_count : _03_;
  assign _06_ = _11_ ? 1'h0 : running;
  assign _07_ = trig_timer - 32'd1;
  assign _08_ = _01_ ? 1'h1 : 1'h0;
  assign _09_ = _01_ ? _04_ : _07_;
  assign _10_ = _01_ ? _05_ : trig_count;
  assign _11_ = _02_ & _01_;
  assign _12_ = go_i ? trig_period_i : trig_timer;
  assign _13_ = go_i ? ntrig_i : trig_count;
  assign _14_ = go_i ? 1'h1 : running;
  assign _15_ = running ? _08_ : 1'h0;
  assign _16_ = running ? _09_ : _12_;
  assign _17_ = running ? _10_ : _13_;
  assign _18_ = running ? _06_ : _14_;
  assign _19_ = rst_i ? 1'h0 : _15_;
  assign _20_ = rst_i ? 32'd0 : _16_;
  assign _21_ = rst_i ? 32'd0 : _17_;
  assign _22_ = rst_i ? 1'h0 : _18_;
  always @(posedge clk_i)
    _23_ <= _00_;
  always @(posedge clk_i)
    _24_ <= _19_;
  always @(posedge clk_i)
    _25_ <= _20_;
  always @(posedge clk_i)
    _26_ <= _21_;
  always @(posedge clk_i)
    _27_ <= _22_;
  assign trig_timer = _25_;
  assign trig_count = _26_;
  assign running = _27_;
  assign busy_o = _23_;
  assign trig_o = _24_;
endmodule

module tt_um_emiliopeju_lightscan(clk, ui_in, uio_in, ena, rst_n, uo_out, uio_out, uio_oe);
  input clk;
  wire clk;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  input ena;
  wire ena;
  input rst_n;
  wire rst_n;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  wire _00_;
  wire [5:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [50:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [31:0] _13_;
  wire [31:0] _14_;
  wire [25:0] _15_;
  wire _16_;
  wire _17_;
  wire [7:0] _18_;
  wire acq_start;
  wire biss_data_sync;
  wire bissc_go;
  wire [7:0] bissc_half_clk_period;
  wire [5:0] bissc_n_rising_edges;
  wire [31:0] ntrig;
  wire [50:0] pos;
  wire pos_err;
  wire pos_req;
  wire pos_valid;
  wire rst;
  wire trig;
  wire [31:0] trig_period;
  wire [25:0] width;
  assign _00_ = ~ rst_n;
  assign _11_ = pos_req | trig;
  bissc_Barch bissc_inst (
    .clk_i(clk),
    .clk_o(_10_),
    .data_i(biss_data_sync),
    .err_o(_09_),
    .go_i(bissc_go),
    .half_clk_period_i(bissc_half_clk_period),
    .n_rising_edges_i(bissc_n_rising_edges),
    .pos_o(_07_),
    .rst_i(rst),
    .valid_o(_08_)
  );
  deglitcher_Brtl_3 deglitcher_inst (
    .bit_i(biss_data_sync),
    .bit_o(_06_),
    .clk_i(clk)
  );
  pulsed_trigger_Brtl pulsed_trigger_inst (
    .busy_o(_02_),
    .clk_i(clk),
    .go_i(acq_start),
    .ntrig_i(ntrig),
    .pulse_o(_04_),
    .rst_i(rst),
    .trig_o(_03_),
    .trig_period_i(trig_period),
    .width_i(width)
  );
  spi_registers_Brtl reg_inst (
    .acq_start_o(_17_),
    .bissc_half_clk_period_o(_18_),
    .bissc_n_rising_edges_o(_01_),
    .clk_i(clk),
    .cs_i(ui_in[0]),
    .error_event_i(pos_err),
    .ntrig_o(_13_),
    .pos_i(pos[31:0]),
    .pos_req_o(_16_),
    .pos_valid_i(pos_valid),
    .rst_i(rst),
    .rx_i(ui_in[2]),
    .sck_i(ui_in[1]),
    .trig_period_o(_14_),
    .tx_o(_12_),
    .width_o(_15_)
  );
  sync_bit_Brtl sync_biss_data_inst (
    .bit_i(uio_in[1]),
    .bit_o(_05_),
    .clk_i(clk)
  );
  assign pos = _07_;
  assign pos_valid = _08_;
  assign pos_err = _09_;
  assign pos_req = _16_;
  assign rst = _00_;
  assign biss_data_sync = _05_;
  assign bissc_go = _11_;
  assign acq_start = _17_;
  assign trig = _03_;
  assign trig_period = _14_;
  assign ntrig = _13_;
  assign width = _15_;
  assign bissc_half_clk_period = _18_;
  assign bissc_n_rising_edges = _01_;
  assign uo_out = { 4'hz, _12_, 1'hz, _04_, _02_ };
  assign uio_out = { 7'hzz, _10_ };
  assign uio_oe = 8'h01;
endmodule
