/* Generated by Yosys 0.62 (git sha1 v0.62, g++ 15.2.0 -fPIC -O3) */

module bissc_Barch(clk_i, rst_i, go_i, half_clk_period_i, n_rising_edges_i, data_i, pos_o, valid_o, err_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input data_i;
  wire data_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  output clk_o;
  wire clk_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [50:0] _4_;
  wire _5_;
  wire _6_;
  wire clock_done;
  wire data;
  wire samp;
  bissc_capture_Brtl bissc_capture_inst (
    .clk_i(clk_i),
    .data_i(data),
    .done_i(clock_done),
    .err_o(_6_),
    .go_i(go_i),
    .pos_o(_4_),
    .rst_i(rst_i),
    .samp_i(samp),
    .valid_o(_5_)
  );
  bissc_extended_clock_Brtl bissc_extended_clock_inst (
    .clk_i(clk_i),
    .clk_o(_3_),
    .data_i(data_i),
    .data_o(_2_),
    .done_o(_0_),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i),
    .samp_o(_1_)
  );
  assign clock_done = _0_;
  assign data = _2_;
  assign samp = _1_;
  assign pos_o = _4_;
  assign valid_o = _5_;
  assign err_o = _6_;
  assign clk_o = _3_;
endmodule

module bissc_capture_Brtl(clk_i, rst_i, go_i, samp_i, data_i, done_i, pos_o, valid_o, err_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input samp_i;
  wire samp_i;
  input data_i;
  wire data_i;
  input done_i;
  wire done_i;
  output [50:0] pos_o;
  wire [50:0] pos_o;
  output valid_o;
  wire valid_o;
  output err_o;
  wire err_o;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [2:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [5:0] _11_;
  wire [58:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [50:0] _17_;
  wire _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire [50:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  wire [2:0] _26_;
  wire [5:0] _27_;
  wire [58:0] _28_;
  wire [50:0] _29_;
  wire _30_;
  wire _31_;
  wire [1:0] _32_;
  wire [2:0] _33_;
  wire [5:0] _34_;
  wire [58:0] _35_;
  reg [50:0] _36_;
  reg _37_;
  reg _38_;
  reg [1:0] _39_ = 2'h0;
  reg [2:0] _40_;
  reg [5:0] _41_;
  reg [58:0] _42_;
  wire [5:0] crc;
  wire [2:0] initial_bits;
  wire [58:0] shift_pos;
  wire [1:0] state;
  assign _00_ = go_i ? 2'h1 : state;
  assign _01_ = state == 2'h0;
  assign _02_ = done_i ? 1'h1 : 1'h0;
  assign _03_ = done_i ? 2'h0 : state;
  assign _04_ = { initial_bits[1:0], data_i } == 3'h2;
  assign _05_ = _06_ ? 2'h2 : _03_;
  assign _06_ = _04_ & samp_i;
  assign _07_ = samp_i ? { initial_bits[1:0], data_i } : initial_bits;
  assign _08_ = state == 2'h1;
  assign _09_ = crc[0] ^ crc[5];
  assign _10_ = data_i ^ crc[5];
  assign _11_ = samp_i ? { crc[4:1], _09_, _10_ } : crc;
  assign _12_ = samp_i ? { shift_pos[57:0], data_i } : shift_pos;
  assign _13_ = crc != 6'h3f;
  assign _14_ = ~ shift_pos[7];
  assign _15_ = _13_ | _14_;
  assign _16_ = _15_ ? 1'h1 : 1'h0;
  assign _17_ = done_i ? shift_pos[58:8] : _36_;
  assign _18_ = done_i ? 1'h1 : 1'h0;
  assign _19_ = done_i ? _16_ : 1'h0;
  assign _20_ = done_i ? 2'h0 : state;
  assign _21_ = state == 2'h2;
  function [50:0] \:636 ;
    input [50:0] a;
    input [152:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:636  = b[50:0];
      3'b?1?:
        \:636  = b[101:51];
      3'b1??:
        \:636  = b[152:102];
      default:
        \:636  = a;
    endcase
  endfunction
  assign _22_ = \:636 (51'hxxxxxxxxxxxxx, { _17_, _36_, _36_ }, { _21_, _08_, _01_ });
  function [0:0] \:639 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:639  = b[0:0];
      3'b?1?:
        \:639  = b[1:1];
      3'b1??:
        \:639  = b[2:2];
      default:
        \:639  = a;
    endcase
  endfunction
  assign _23_ = \:639 (1'hx, { _18_, 2'h0 }, { _21_, _08_, _01_ });
  function [0:0] \:642 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:642  = b[0:0];
      3'b?1?:
        \:642  = b[1:1];
      3'b1??:
        \:642  = b[2:2];
      default:
        \:642  = a;
    endcase
  endfunction
  assign _24_ = \:642 (1'hx, { _19_, _02_, 1'h0 }, { _21_, _08_, _01_ });
  function [1:0] \:644 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:644  = b[1:0];
      3'b?1?:
        \:644  = b[3:2];
      3'b1??:
        \:644  = b[5:4];
      default:
        \:644  = a;
    endcase
  endfunction
  assign _25_ = \:644 (2'hx, { _20_, _05_, _00_ }, { _21_, _08_, _01_ });
  function [2:0] \:647 ;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:647  = b[2:0];
      3'b?1?:
        \:647  = b[5:3];
      3'b1??:
        \:647  = b[8:6];
      default:
        \:647  = a;
    endcase
  endfunction
  assign _26_ = \:647 (3'hx, { initial_bits, _07_, 3'h0 }, { _21_, _08_, _01_ });
  function [5:0] \:650 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:650  = b[5:0];
      3'b?1?:
        \:650  = b[11:6];
      3'b1??:
        \:650  = b[17:12];
      default:
        \:650  = a;
    endcase
  endfunction
  assign _27_ = \:650 (6'hxx, { _11_, crc, 6'h00 }, { _21_, _08_, _01_ });
  function [58:0] \:653 ;
    input [58:0] a;
    input [176:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:653  = b[58:0];
      3'b?1?:
        \:653  = b[117:59];
      3'b1??:
        \:653  = b[176:118];
      default:
        \:653  = a;
    endcase
  endfunction
  assign _28_ = \:653 (59'hxxxxxxxxxxxxxxx, { _12_, shift_pos, 59'h000000000000000 }, { _21_, _08_, _01_ });
  assign _29_ = rst_i ? _36_ : _22_;
  assign _30_ = rst_i ? 1'h0 : _23_;
  assign _31_ = rst_i ? 1'h0 : _24_;
  assign _32_ = rst_i ? 2'h0 : _25_;
  assign _33_ = rst_i ? initial_bits : _26_;
  assign _34_ = rst_i ? crc : _27_;
  assign _35_ = rst_i ? shift_pos : _28_;
  always @(posedge clk_i)
    _36_ <= _29_;
  always @(posedge clk_i)
    _37_ <= _30_;
  always @(posedge clk_i)
    _38_ <= _31_;
  always @(posedge clk_i)
    _39_ <= _32_;
  always @(posedge clk_i)
    _40_ <= _33_;
  always @(posedge clk_i)
    _41_ <= _34_;
  always @(posedge clk_i)
    _42_ <= _35_;
  assign state = _39_;
  assign initial_bits = _40_;
  assign crc = _41_;
  assign shift_pos = _42_;
  assign pos_o = _36_;
  assign valid_o = _37_;
  assign err_o = _38_;
endmodule

module bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire _09_;
  wire [1:0] _10_;
  wire [5:0] _11_;
  wire _12_;
  wire _13_;
  wire [5:0] _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire [7:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [1:0] _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire [7:0] _28_;
  wire [1:0] _29_;
  wire [5:0] _30_;
  wire _31_;
  wire _32_;
  wire [7:0] _33_;
  wire [1:0] _34_;
  wire [5:0] _35_;
  reg _36_;
  reg _37_;
  reg [7:0] _38_;
  reg [1:0] _39_;
  reg [5:0] _40_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _36_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _37_;
  assign _06_ = ~ _37_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 1'h0 : _36_;
  assign _10_ = _19_ ? 2'h0 : clock_state;
  assign _11_ = _07_ ? rising_counter : _08_;
  assign _12_ = _07_ & _06_;
  assign _13_ = _07_ & _06_;
  assign _14_ = _20_ ? _11_ : rising_counter;
  assign _15_ = clock_timer - 8'h01;
  assign _16_ = _12_ & _04_;
  assign _17_ = _04_ ? _05_ : _37_;
  assign _18_ = _04_ ? half_clk_period_i : _15_;
  assign _19_ = _13_ & _04_;
  assign _20_ = _06_ & _04_;
  assign _21_ = clock_state == 2'h1;
  assign _22_ = data_i | go_i;
  assign _23_ = _22_ ? 1'h0 : _36_;
  assign _24_ = _22_ ? 2'h0 : clock_state;
  assign _25_ = clock_state == 2'h2;
  function [0:0] \:796 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:796  = b[0:0];
      3'b?1?:
        \:796  = b[1:1];
      3'b1??:
        \:796  = b[2:2];
      default:
        \:796  = a;
    endcase
  endfunction
  assign _26_ = \:796 (_36_, { _23_, _09_, _00_ }, { _25_, _21_, _03_ });
  function [0:0] \:797 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:797  = b[0:0];
      3'b?1?:
        \:797  = b[1:1];
      3'b1??:
        \:797  = b[2:2];
      default:
        \:797  = a;
    endcase
  endfunction
  assign _27_ = \:797 (_37_, { _37_, _17_, _01_ }, { _25_, _21_, _03_ });
  function [7:0] \:798 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:798  = b[7:0];
      3'b?1?:
        \:798  = b[15:8];
      3'b1??:
        \:798  = b[23:16];
      default:
        \:798  = a;
    endcase
  endfunction
  assign _28_ = \:798 (clock_timer, { clock_timer, _18_, half_clk_period_i }, { _25_, _21_, _03_ });
  function [1:0] \:799 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:799  = b[1:0];
      3'b?1?:
        \:799  = b[3:2];
      3'b1??:
        \:799  = b[5:4];
      default:
        \:799  = a;
    endcase
  endfunction
  assign _29_ = \:799 (clock_state, { _24_, _10_, _02_ }, { _25_, _21_, _03_ });
  function [5:0] \:800 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:800  = b[5:0];
      3'b?1?:
        \:800  = b[11:6];
      3'b1??:
        \:800  = b[17:12];
      default:
        \:800  = a;
    endcase
  endfunction
  assign _30_ = \:800 (rising_counter, { rising_counter, _14_, n_rising_edges_i }, { _25_, _21_, _03_ });
  assign _31_ = rst_i ? 1'h0 : _26_;
  assign _32_ = rst_i ? _37_ : _27_;
  assign _33_ = rst_i ? clock_timer : _28_;
  assign _34_ = rst_i ? 2'h0 : _29_;
  assign _35_ = rst_i ? rising_counter : _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  always @(posedge clk_i)
    _38_ <= _33_;
  always @(posedge clk_i)
    _39_ <= _34_;
  always @(posedge clk_i)
    _40_ <= _35_;
  assign clock_timer = _38_;
  assign clock_state = _39_;
  assign rising_counter = _40_;
  assign busy_o = _36_;
  assign clk_o = _37_;
endmodule

module bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, busy_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output busy_o;
  wire busy_o;
  output clk_o;
  wire clk_o;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [5:0] _08_;
  wire [1:0] _09_;
  wire [5:0] _10_;
  wire _11_;
  wire [5:0] _12_;
  wire [7:0] _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire [1:0] _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [7:0] _25_;
  wire [1:0] _26_;
  wire [5:0] _27_;
  wire _28_;
  wire _29_;
  wire [7:0] _30_;
  wire [1:0] _31_;
  wire [5:0] _32_;
  reg _33_;
  reg _34_;
  reg [7:0] _35_;
  reg [1:0] _36_;
  reg [5:0] _37_;
  wire [1:0] clock_state;
  wire [7:0] clock_timer;
  wire [5:0] rising_counter;
  assign _00_ = go_i ? 1'h1 : _33_;
  assign _01_ = go_i ? 1'h0 : 1'h1;
  assign _02_ = go_i ? 2'h1 : clock_state;
  assign _03_ = clock_state == 2'h0;
  assign _04_ = clock_timer == 8'h00;
  assign _05_ = ~ _34_;
  assign _06_ = ~ _34_;
  assign _07_ = rising_counter == 6'h00;
  assign _08_ = rising_counter - 6'h01;
  assign _09_ = _16_ ? 2'h2 : clock_state;
  assign _10_ = _07_ ? rising_counter : _08_;
  assign _11_ = _07_ & _06_;
  assign _12_ = _17_ ? _10_ : rising_counter;
  assign _13_ = clock_timer - 8'h01;
  assign _14_ = _04_ ? _05_ : _34_;
  assign _15_ = _04_ ? half_clk_period_i : _13_;
  assign _16_ = _11_ & _04_;
  assign _17_ = _06_ & _04_;
  assign _18_ = clock_state == 2'h1;
  assign _19_ = data_i | go_i;
  assign _20_ = _19_ ? 1'h0 : _33_;
  assign _21_ = _19_ ? 2'h0 : clock_state;
  assign _22_ = clock_state == 2'h2;
  function [0:0] \:727 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:727  = b[0:0];
      3'b?1?:
        \:727  = b[1:1];
      3'b1??:
        \:727  = b[2:2];
      default:
        \:727  = a;
    endcase
  endfunction
  assign _23_ = \:727 (_33_, { _20_, _33_, _00_ }, { _22_, _18_, _03_ });
  function [0:0] \:728 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:728  = b[0:0];
      3'b?1?:
        \:728  = b[1:1];
      3'b1??:
        \:728  = b[2:2];
      default:
        \:728  = a;
    endcase
  endfunction
  assign _24_ = \:728 (_34_, { _34_, _14_, _01_ }, { _22_, _18_, _03_ });
  function [7:0] \:729 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:729  = b[7:0];
      3'b?1?:
        \:729  = b[15:8];
      3'b1??:
        \:729  = b[23:16];
      default:
        \:729  = a;
    endcase
  endfunction
  assign _25_ = \:729 (clock_timer, { clock_timer, _15_, half_clk_period_i }, { _22_, _18_, _03_ });
  function [1:0] \:730 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:730  = b[1:0];
      3'b?1?:
        \:730  = b[3:2];
      3'b1??:
        \:730  = b[5:4];
      default:
        \:730  = a;
    endcase
  endfunction
  assign _26_ = \:730 (clock_state, { _21_, _09_, _02_ }, { _22_, _18_, _03_ });
  function [5:0] \:731 ;
    input [5:0] a;
    input [17:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:731  = b[5:0];
      3'b?1?:
        \:731  = b[11:6];
      3'b1??:
        \:731  = b[17:12];
      default:
        \:731  = a;
    endcase
  endfunction
  assign _27_ = \:731 (rising_counter, { rising_counter, _12_, n_rising_edges_i }, { _22_, _18_, _03_ });
  assign _28_ = rst_i ? 1'h0 : _23_;
  assign _29_ = rst_i ? _34_ : _24_;
  assign _30_ = rst_i ? clock_timer : _25_;
  assign _31_ = rst_i ? 2'h0 : _26_;
  assign _32_ = rst_i ? rising_counter : _27_;
  always @(posedge clk_i)
    _33_ <= _28_;
  always @(posedge clk_i)
    _34_ <= _29_;
  always @(posedge clk_i)
    _35_ <= _30_;
  always @(posedge clk_i)
    _36_ <= _31_;
  always @(posedge clk_i)
    _37_ <= _32_;
  assign clock_timer = _35_;
  assign clock_state = _36_;
  assign rising_counter = _37_;
  assign busy_o = _33_;
  assign clk_o = _34_;
endmodule

module bissc_extended_clock_Brtl(clk_i, rst_i, go_i, n_rising_edges_i, half_clk_period_i, data_i, done_o, samp_o, data_o, clk_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [5:0] n_rising_edges_i;
  wire [5:0] n_rising_edges_i;
  input [7:0] half_clk_period_i;
  wire [7:0] half_clk_period_i;
  input data_i;
  wire data_i;
  output done_o;
  wire done_o;
  output samp_o;
  wire samp_o;
  output data_o;
  wire data_o;
  output clk_o;
  wire clk_o;
  wire [5:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [1:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [1:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [1:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  reg _26_;
  reg _27_;
  reg _28_;
  reg [1:0] _29_ = 2'h0;
  reg _30_;
  reg _31_;
  wire busy1;
  wire busy2;
  wire data_dly;
  wire data_dly2;
  wire go2;
  wire [5:0] nbits;
  wire samp_clk;
  wire samp_clk_dly;
  wire samp_clk_rise;
  wire [1:0] state;
  assign _00_ = n_rising_edges_i - 6'h02;
  assign _05_ = ~ samp_clk_dly;
  assign _06_ = samp_clk & _05_;
  assign _07_ = go_i ? 2'h1 : state;
  assign _08_ = state == 2'h0;
  assign _09_ = ~ data_i;
  assign _10_ = go_i ? 2'h2 : state;
  assign _11_ = _09_ ? 1'h1 : 1'h0;
  assign _12_ = _09_ ? 2'h2 : _10_;
  assign _13_ = state == 2'h1;
  assign _14_ = ~ busy1;
  assign _15_ = ~ busy2;
  assign _16_ = _14_ & _15_;
  assign _17_ = _16_ ? 1'h1 : 1'h0;
  assign _18_ = _16_ ? 2'h0 : state;
  assign _19_ = state == 2'h2;
  function [0:0] \:552 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:552  = b[0:0];
      3'b?1?:
        \:552  = b[1:1];
      3'b1??:
        \:552  = b[2:2];
      default:
        \:552  = a;
    endcase
  endfunction
  assign _20_ = \:552 (1'h0, { _17_, 2'h0 }, { _19_, _13_, _08_ });
  function [0:0] \:555 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:555  = b[0:0];
      3'b?1?:
        \:555  = b[1:1];
      3'b1??:
        \:555  = b[2:2];
      default:
        \:555  = a;
    endcase
  endfunction
  assign _21_ = \:555 (1'h0, { 1'h0, _11_, 1'h0 }, { _19_, _13_, _08_ });
  function [1:0] \:556 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:556  = b[1:0];
      3'b?1?:
        \:556  = b[3:2];
      3'b1??:
        \:556  = b[5:4];
      default:
        \:556  = a;
    endcase
  endfunction
  assign _22_ = \:556 (state, { _18_, _12_, _07_ }, { _19_, _13_, _08_ });
  assign _23_ = rst_i ? _26_ : _20_;
  assign _24_ = rst_i ? 1'h0 : _21_;
  assign _25_ = rst_i ? 2'h0 : _22_;
  always @(posedge clk_i)
    _26_ <= _23_;
  always @(posedge clk_i)
    _27_ <= samp_clk;
  always @(posedge clk_i)
    _28_ <= _24_;
  always @(posedge clk_i)
    _29_ <= _25_;
  always @(posedge clk_i)
    _30_ <= data_i;
  always @(posedge clk_i)
    _31_ <= data_dly;
  bissc_clock_Brtl_f70af62ee4cd5ae2b0ba027eb472ca7c56eacd2e bissc_clock_inst (
    .busy_o(_01_),
    .clk_i(clk_i),
    .clk_o(_02_),
    .data_i(data_i),
    .go_i(go_i),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(n_rising_edges_i),
    .rst_i(rst_i)
  );
  bissc_clock_Brtl_688934845f22049cb14668832efa33d45013b6b9 bissc_samp_clock_inst (
    .busy_o(_03_),
    .clk_i(clk_i),
    .clk_o(_04_),
    .data_i(data_i),
    .go_i(go2),
    .half_clk_period_i(half_clk_period_i),
    .n_rising_edges_i(nbits),
    .rst_i(rst_i)
  );
  assign nbits = _00_;
  assign samp_clk = _04_;
  assign samp_clk_dly = _27_;
  assign samp_clk_rise = _06_;
  assign go2 = _28_;
  assign state = _29_;
  assign data_dly = _30_;
  assign data_dly2 = _31_;
  assign busy1 = _01_;
  assign busy2 = _03_;
  assign done_o = _26_;
  assign samp_o = samp_clk_rise;
  assign data_o = data_dly2;
  assign clk_o = _02_;
endmodule

module deglitcher_Brtl_3(clk_i, bit_i, bit_o);
  input clk_i;
  wire clk_i;
  input bit_i;
  wire bit_i;
  output bit_o;
  wire bit_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  reg _4_;
  reg [2:0] _5_;
  wire [2:0] bit_shift;
  assign _0_ = bit_shift == 3'h7;
  assign _1_ = bit_shift == 3'h0;
  assign _2_ = _1_ ? 1'h0 : _4_;
  assign _3_ = _0_ ? 1'h1 : _2_;
  always @(posedge clk_i)
    _4_ <= _3_;
  always @(posedge clk_i)
    _5_ <= { bit_shift[1:0], bit_i };
  assign bit_shift = _5_;
  assign bit_o = _4_;
endmodule

module pulse_stretch_Brtl(clk_i, rst_i, width_i, trig_i, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  input trig_i;
  wire trig_i;
  output pulse_o;
  wire pulse_o;
  wire _00_;
  wire _01_;
  wire [25:0] _02_;
  wire [25:0] _03_;
  wire _04_;
  wire [25:0] _05_;
  wire _06_;
  wire [25:0] _07_;
  wire _08_;
  reg [25:0] _09_;
  reg _10_;
  wire pulse;
  wire [25:0] pulse_timer;
  assign _00_ = pulse | trig_i;
  assign _01_ = pulse_timer != 26'h0000000;
  assign _02_ = pulse_timer - 26'h0000001;
  assign _03_ = _01_ ? _02_ : pulse_timer;
  assign _04_ = _01_ ? 1'h1 : 1'h0;
  assign _05_ = trig_i ? width_i : _03_;
  assign _06_ = trig_i ? 1'h1 : _04_;
  assign _07_ = rst_i ? 26'h0000000 : _05_;
  assign _08_ = rst_i ? 1'h0 : _06_;
  always @(posedge clk_i)
    _09_ <= _07_;
  always @(posedge clk_i)
    _10_ <= _08_;
  assign pulse_timer = _09_;
  assign pulse = _10_;
  assign pulse_o = _00_;
endmodule

module pulsed_trigger_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, width_i, busy_o, trig_o, pulse_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  input [25:0] width_i;
  wire [25:0] width_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  output pulse_o;
  wire pulse_o;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire busy;
  wire trig;
  assign _0_ = busy | _1_;
  pulse_stretch_Brtl pulse_stretch_inst (
    .clk_i(clk_i),
    .pulse_o(_1_),
    .rst_i(rst_i),
    .trig_i(trig),
    .width_i(width_i)
  );
  trigger_generator_Brtl trig_gen_inst (
    .busy_o(_2_),
    .clk_i(clk_i),
    .go_i(go_i),
    .ntrig_i(ntrig_i),
    .rst_i(rst_i),
    .trig_o(_3_),
    .trig_period_i(trig_period_i)
  );
  assign trig = _3_;
  assign busy = _2_;
  assign busy_o = _0_;
  assign trig_o = trig;
  assign pulse_o = _1_;
endmodule

module spi_registers_Brtl(clk_i, rst_i, cs_i, sck_i, rx_i, trig_i, pos_i, pos_valid_i, error_event_i, io_in_i, tx_o, override_trig_o, ntrig_o, trig_period_o, width_o, pos_req_o, acq_start_o, bissc_half_clk_period_o, bissc_n_rising_edges_o, io_dir_o, io_out_o
);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input cs_i;
  wire cs_i;
  input sck_i;
  wire sck_i;
  input rx_i;
  wire rx_i;
  input trig_i;
  wire trig_i;
  input [50:0] pos_i;
  wire [50:0] pos_i;
  input pos_valid_i;
  wire pos_valid_i;
  input error_event_i;
  wire error_event_i;
  input [5:0] io_in_i;
  wire [5:0] io_in_i;
  output tx_o;
  wire tx_o;
  output override_trig_o;
  wire override_trig_o;
  output [31:0] ntrig_o;
  wire [31:0] ntrig_o;
  output [31:0] trig_period_o;
  wire [31:0] trig_period_o;
  output [25:0] width_o;
  wire [25:0] width_o;
  output pos_req_o;
  wire pos_req_o;
  output acq_start_o;
  wire acq_start_o;
  output [7:0] bissc_half_clk_period_o;
  wire [7:0] bissc_half_clk_period_o;
  output [5:0] bissc_n_rising_edges_o;
  wire [5:0] bissc_n_rising_edges_o;
  output [5:0] io_dir_o;
  wire [5:0] io_dir_o;
  output [5:0] io_out_o;
  wire [5:0] io_out_o;
  wire [31:0] _000_;
  wire _001_;
  wire [5:0] _002_;
  wire [5:0] _003_;
  wire _004_;
  wire [31:0] _005_;
  wire _006_;
  wire _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [25:0] _010_;
  wire _011_;
  wire _012_;
  wire [7:0] _013_;
  wire [5:0] _014_;
  wire [5:0] _015_;
  wire [5:0] _016_;
  wire [31:0] _017_;
  wire [39:0] _018_;
  wire [5:0] _019_;
  wire _020_;
  wire [5:0] _021_;
  wire [5:0] _022_;
  wire _023_;
  wire _024_;
  wire [31:0] _025_;
  wire [31:0] _026_;
  wire [25:0] _027_;
  wire _028_;
  wire _029_;
  wire [7:0] _030_;
  wire [5:0] _031_;
  wire [5:0] _032_;
  wire [5:0] _033_;
  wire [31:0] _034_;
  wire [39:0] _035_;
  wire [5:0] _036_;
  wire _037_;
  wire [5:0] _038_;
  wire [5:0] _039_;
  wire _040_;
  wire _041_;
  wire [31:0] _042_;
  wire [31:0] _043_;
  wire [25:0] _044_;
  wire _045_;
  wire _046_;
  wire [7:0] _047_;
  wire [5:0] _048_;
  wire [5:0] _049_;
  wire [5:0] _050_;
  wire [31:0] _051_;
  wire [39:0] _052_;
  wire [5:0] _053_;
  wire [7:0] _054_;
  wire _055_;
  wire [5:0] _056_;
  wire [5:0] _057_;
  wire [7:0] _058_;
  wire [7:0] _059_;
  wire _060_;
  wire _061_;
  wire [5:0] _062_;
  wire [5:0] _063_;
  reg _064_;
  reg _065_;
  reg [31:0] _066_;
  reg [31:0] _067_;
  reg [25:0] _068_;
  reg _069_;
  reg _070_;
  reg [7:0] _071_;
  reg [5:0] _072_;
  reg [5:0] _073_;
  reg [5:0] _074_;
  reg [31:0] _075_;
  reg [39:0] _076_;
  reg _077_;
  reg _078_;
  reg [5:0] _079_;
  reg [7:0] _080_;
  reg [7:0] _081_;
  reg [15:0] _082_;
  reg _083_;
  reg [5:0] _084_;
  reg [5:0] _085_;
  wire [5:0] _086_;
  reg [5:0] _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire [15:0] _097_;
  wire [15:0] _098_;
  wire [7:0] _099_;
  wire [7:0] _100_;
  wire [7:0] _101_;
  wire [15:0] _102_;
  wire [5:0] _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire [5:0] _116_;
  wire [1:0] _117_;
  wire [17:0] _118_;
  wire [5:0] _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [25:0] _133_;
  wire _134_;
  wire _135_;
  wire [7:0] _136_;
  wire [5:0] _137_;
  wire [5:0] _138_;
  wire [5:0] _139_;
  wire [5:0] _140_;
  wire [5:0] _141_;
  wire _142_;
  wire [31:0] _143_;
  wire [31:0] _144_;
  wire [25:0] _145_;
  wire _146_;
  wire _147_;
  wire [7:0] _148_;
  wire [5:0] _149_;
  wire [5:0] _150_;
  wire [5:0] _151_;
  wire [5:0] _152_;
  wire [5:0] _153_;
  wire _154_;
  wire [31:0] _155_;
  wire [31:0] _156_;
  wire [25:0] _157_;
  wire _158_;
  wire _159_;
  wire [7:0] _160_;
  wire [5:0] _161_;
  wire [5:0] _162_;
  wire [5:0] _163_;
  wire [5:0] bit_counter;
  wire cs;
  wire cs_fall;
  wire cs_prev;
  wire [39:0] datain;
  wire [31:0] dataout;
  wire [5:0] io_dir;
  wire [5:0] io_in;
  wire [5:0] io_out;
  wire [7:0] n_err;
  wire [7:0] n_over;
  wire [15:0] n_pos;
  wire new_pos;
  wire rx;
  wire sck;
  wire sck_fall;
  wire sck_prev;
  wire sck_rise;
  assign _111_ = { datain[6:0], rx } == 8'h06;
  assign _112_ = { datain[6:0], rx } == 8'h07;
  assign _113_ = { datain[6:0], rx } == 8'h08;
  assign _114_ = { datain[6:0], rx } == 8'h0a;
  assign _115_ = { datain[6:0], rx } == 8'h0b;
  function [5:0] \:124 ;
    input [5:0] a;
    input [65:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:124  = b[5:0];
      11'b?????????1?:
        \:124  = b[11:6];
      11'b????????1??:
        \:124  = b[17:12];
      11'b???????1???:
        \:124  = b[23:18];
      11'b??????1????:
        \:124  = b[29:24];
      11'b?????1?????:
        \:124  = b[35:30];
      11'b????1??????:
        \:124  = b[41:36];
      11'b???1???????:
        \:124  = b[47:42];
      11'b??1????????:
        \:124  = b[53:48];
      11'b?1?????????:
        \:124  = b[59:54];
      11'b1??????????:
        \:124  = b[65:60];
      default:
        \:124  = a;
    endcase
  endfunction
  assign _116_ = \:124 (6'h00, { io_in_i, io_in, pos_i[24:19], _072_, _071_[5:0], _068_[5:0], _066_[5:0], _067_[5:0], pos_i[5:0], n_pos[5:0], 6'h1c }, { _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_ });
  function [1:0] \:137 ;
    input [1:0] a;
    input [21:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:137  = b[1:0];
      11'b?????????1?:
        \:137  = b[3:2];
      11'b????????1??:
        \:137  = b[5:4];
      11'b???????1???:
        \:137  = b[7:6];
      11'b??????1????:
        \:137  = b[9:8];
      11'b?????1?????:
        \:137  = b[11:10];
      11'b????1??????:
        \:137  = b[13:12];
      11'b???1???????:
        \:137  = b[15:14];
      11'b??1????????:
        \:137  = b[17:16];
      11'b?1?????????:
        \:137  = b[19:18];
      11'b1??????????:
        \:137  = b[21:20];
      default:
        \:137  = a;
    endcase
  endfunction
  assign _117_ = \:137 (2'h0, { 4'h0, pos_i[26:25], 2'h0, _071_[7:6], _068_[7:6], _066_[7:6], _067_[7:6], pos_i[7:6], n_pos[7:6], 2'h0 }, { _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_ });
  function [17:0] \:150 ;
    input [17:0] a;
    input [197:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:150  = b[17:0];
      11'b?????????1?:
        \:150  = b[35:18];
      11'b????????1??:
        \:150  = b[53:36];
      11'b???????1???:
        \:150  = b[71:54];
      11'b??????1????:
        \:150  = b[89:72];
      11'b?????1?????:
        \:150  = b[107:90];
      11'b????1??????:
        \:150  = b[125:108];
      11'b???1???????:
        \:150  = b[143:126];
      11'b??1????????:
        \:150  = b[161:144];
      11'b?1?????????:
        \:150  = b[179:162];
      11'b1??????????:
        \:150  = b[197:180];
      default:
        \:150  = a;
    endcase
  endfunction
  assign _118_ = \:150 (18'h00000, { 36'h000000000, pos_i[44:27], 36'h000000000, _068_[25:8], _066_[25:8], _067_[25:8], pos_i[25:8], n_over[1:0], n_err, n_pos[15:8], 18'h2fea5 }, { _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_ });
  function [5:0] \:162 ;
    input [5:0] a;
    input [65:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:162  = b[5:0];
      11'b?????????1?:
        \:162  = b[11:6];
      11'b????????1??:
        \:162  = b[17:12];
      11'b???????1???:
        \:162  = b[23:18];
      11'b??????1????:
        \:162  = b[29:24];
      11'b?????1?????:
        \:162  = b[35:30];
      11'b????1??????:
        \:162  = b[41:36];
      11'b???1???????:
        \:162  = b[47:42];
      11'b??1????????:
        \:162  = b[53:48];
      11'b?1?????????:
        \:162  = b[59:54];
      11'b1??????????:
        \:162  = b[65:60];
      default:
        \:162  = a;
    endcase
  endfunction
  assign _119_ = \:162 (6'h00, { 12'h000, pos_i[50:45], 18'h00000, _066_[31:26], _067_[31:26], pos_i[31:26], n_over[7:2], 6'h32 }, { _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_ });
  function [0:0] \:164 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \:164  = b[0:0];
      11'b?????????1?:
        \:164  = b[1:1];
      11'b????????1??:
        \:164  = b[2:2];
      11'b???????1???:
        \:164  = b[3:3];
      11'b??????1????:
        \:164  = b[4:4];
      11'b?????1?????:
        \:164  = b[5:5];
      11'b????1??????:
        \:164  = b[6:6];
      11'b???1???????:
        \:164  = b[7:7];
      11'b??1????????:
        \:164  = b[8:8];
      11'b?1?????????:
        \:164  = b[9:9];
      11'b1??????????:
        \:164  = b[10:10];
      default:
        \:164  = a;
    endcase
  endfunction
  assign _120_ = \:164 (new_pos, { new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, new_pos, 1'h0, new_pos, new_pos }, { _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_ });
  assign _121_ = bit_counter == 6'h27;
  assign _122_ = datain[38:31] == 8'h83;
  assign _123_ = datain[38:31] == 8'h84;
  assign _124_ = datain[38:31] == 8'h85;
  assign _125_ = datain[38:31] == 8'h86;
  assign _126_ = datain[38:31] == 8'h87;
  assign _127_ = datain[38:31] == 8'h89;
  assign _128_ = datain[38:31] == 8'h8a;
  assign _129_ = datain[38:31] == 8'h8b;
  function [0:0] \:198 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:198  = b[0:0];
      8'b??????1?:
        \:198  = b[1:1];
      8'b?????1??:
        \:198  = b[2:2];
      8'b????1???:
        \:198  = b[3:3];
      8'b???1????:
        \:198  = b[4:4];
      8'b??1?????:
        \:198  = b[5:5];
      8'b?1??????:
        \:198  = b[6:6];
      8'b1???????:
        \:198  = b[7:7];
      default:
        \:198  = a;
    endcase
  endfunction
  assign _130_ = \:198 (1'h0, { 2'h0, datain[1], 5'h00 }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [31:0] \:199 ;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:199  = b[31:0];
      8'b??????1?:
        \:199  = b[63:32];
      8'b?????1??:
        \:199  = b[95:64];
      8'b????1???:
        \:199  = b[127:96];
      8'b???1????:
        \:199  = b[159:128];
      8'b??1?????:
        \:199  = b[191:160];
      8'b?1??????:
        \:199  = b[223:192];
      8'b1???????:
        \:199  = b[255:224];
      default:
        \:199  = a;
    endcase
  endfunction
  assign _131_ = \:199 (_066_, { _066_, _066_, _066_, _066_, _066_, _066_, datain[30:0], rx, _066_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [31:0] \:200 ;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:200  = b[31:0];
      8'b??????1?:
        \:200  = b[63:32];
      8'b?????1??:
        \:200  = b[95:64];
      8'b????1???:
        \:200  = b[127:96];
      8'b???1????:
        \:200  = b[159:128];
      8'b??1?????:
        \:200  = b[191:160];
      8'b?1??????:
        \:200  = b[223:192];
      8'b1???????:
        \:200  = b[255:224];
      default:
        \:200  = a;
    endcase
  endfunction
  assign _132_ = \:200 (_067_, { _067_, _067_, _067_, _067_, _067_, _067_, _067_, datain[30:0], rx }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [25:0] \:201 ;
    input [25:0] a;
    input [207:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:201  = b[25:0];
      8'b??????1?:
        \:201  = b[51:26];
      8'b?????1??:
        \:201  = b[77:52];
      8'b????1???:
        \:201  = b[103:78];
      8'b???1????:
        \:201  = b[129:104];
      8'b??1?????:
        \:201  = b[155:130];
      8'b?1??????:
        \:201  = b[181:156];
      8'b1???????:
        \:201  = b[207:182];
      default:
        \:201  = a;
    endcase
  endfunction
  assign _133_ = \:201 (_068_, { _068_, _068_, _068_, _068_, _068_, datain[24:0], rx, _068_, _068_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [0:0] \:203 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:203  = b[0:0];
      8'b??????1?:
        \:203  = b[1:1];
      8'b?????1??:
        \:203  = b[2:2];
      8'b????1???:
        \:203  = b[3:3];
      8'b???1????:
        \:203  = b[4:4];
      8'b??1?????:
        \:203  = b[5:5];
      8'b?1??????:
        \:203  = b[6:6];
      8'b1???????:
        \:203  = b[7:7];
      default:
        \:203  = a;
    endcase
  endfunction
  assign _134_ = \:203 (1'h0, { 2'h0, rx, 5'h00 }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [0:0] \:205 ;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:205  = b[0:0];
      8'b??????1?:
        \:205  = b[1:1];
      8'b?????1??:
        \:205  = b[2:2];
      8'b????1???:
        \:205  = b[3:3];
      8'b???1????:
        \:205  = b[4:4];
      8'b??1?????:
        \:205  = b[5:5];
      8'b?1??????:
        \:205  = b[6:6];
      8'b1???????:
        \:205  = b[7:7];
      default:
        \:205  = a;
    endcase
  endfunction
  assign _135_ = \:205 (1'h0, { 2'h0, datain[0], 5'h00 }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [7:0] \:206 ;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:206  = b[7:0];
      8'b??????1?:
        \:206  = b[15:8];
      8'b?????1??:
        \:206  = b[23:16];
      8'b????1???:
        \:206  = b[31:24];
      8'b???1????:
        \:206  = b[39:32];
      8'b??1?????:
        \:206  = b[47:40];
      8'b?1??????:
        \:206  = b[55:48];
      8'b1???????:
        \:206  = b[63:56];
      default:
        \:206  = a;
    endcase
  endfunction
  assign _136_ = \:206 (_071_, { _071_, _071_, _071_, _071_, datain[6:0], rx, _071_, _071_, _071_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [5:0] \:207 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:207  = b[5:0];
      8'b??????1?:
        \:207  = b[11:6];
      8'b?????1??:
        \:207  = b[17:12];
      8'b????1???:
        \:207  = b[23:18];
      8'b???1????:
        \:207  = b[29:24];
      8'b??1?????:
        \:207  = b[35:30];
      8'b?1??????:
        \:207  = b[41:36];
      8'b1???????:
        \:207  = b[47:42];
      default:
        \:207  = a;
    endcase
  endfunction
  assign _137_ = \:207 (_072_, { _072_, _072_, _072_, datain[4:0], rx, _072_, _072_, _072_, _072_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [5:0] \:208 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:208  = b[5:0];
      8'b??????1?:
        \:208  = b[11:6];
      8'b?????1??:
        \:208  = b[17:12];
      8'b????1???:
        \:208  = b[23:18];
      8'b???1????:
        \:208  = b[29:24];
      8'b??1?????:
        \:208  = b[35:30];
      8'b?1??????:
        \:208  = b[41:36];
      8'b1???????:
        \:208  = b[47:42];
      default:
        \:208  = a;
    endcase
  endfunction
  assign _138_ = \:208 (_073_, { datain[12:7], _073_, _073_, _073_, _073_, _073_, _073_, _073_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [5:0] \:209 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:209  = b[5:0];
      8'b??????1?:
        \:209  = b[11:6];
      8'b?????1??:
        \:209  = b[17:12];
      8'b????1???:
        \:209  = b[23:18];
      8'b???1????:
        \:209  = b[29:24];
      8'b??1?????:
        \:209  = b[35:30];
      8'b?1??????:
        \:209  = b[41:36];
      8'b1???????:
        \:209  = b[47:42];
      default:
        \:209  = a;
    endcase
  endfunction
  assign _139_ = \:209 (_074_, { datain[4:0], rx, _074_, _074_, _074_, _074_, _074_, _074_, _074_ }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [5:0] \:210 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:210  = b[5:0];
      8'b??????1?:
        \:210  = b[11:6];
      8'b?????1??:
        \:210  = b[17:12];
      8'b????1???:
        \:210  = b[23:18];
      8'b???1????:
        \:210  = b[29:24];
      8'b??1?????:
        \:210  = b[35:30];
      8'b?1??????:
        \:210  = b[41:36];
      8'b1???????:
        \:210  = b[47:42];
      default:
        \:210  = a;
    endcase
  endfunction
  assign _140_ = \:210 (io_out, { io_out, datain[4:0], rx, io_out, io_out, io_out, io_out, io_out, io_out }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  function [5:0] \:211 ;
    input [5:0] a;
    input [47:0] b;
    input [7:0] s;
    (* parallel_case *)
    casez (s)
      8'b???????1:
        \:211  = b[5:0];
      8'b??????1?:
        \:211  = b[11:6];
      8'b?????1??:
        \:211  = b[17:12];
      8'b????1???:
        \:211  = b[23:18];
      8'b???1????:
        \:211  = b[29:24];
      8'b??1?????:
        \:211  = b[35:30];
      8'b?1??????:
        \:211  = b[41:36];
      8'b1???????:
        \:211  = b[47:42];
      default:
        \:211  = a;
    endcase
  endfunction
  assign _141_ = \:211 (io_dir, { io_dir, datain[12:7], io_dir, io_dir, io_dir, io_dir, io_dir, io_dir }, { _129_, _128_, _127_, _126_, _125_, _124_, _123_, _122_ });
  assign _142_ = _121_ ? _130_ : 1'h0;
  assign _143_ = _121_ ? _131_ : _066_;
  assign _144_ = _121_ ? _132_ : _067_;
  assign _145_ = _121_ ? _133_ : _068_;
  assign _146_ = _121_ ? _134_ : 1'h0;
  assign _147_ = _121_ ? _135_ : 1'h0;
  assign _148_ = _121_ ? _136_ : _071_;
  assign _149_ = _121_ ? _137_ : _072_;
  assign _150_ = _121_ ? _138_ : _073_;
  assign _151_ = _121_ ? _139_ : _074_;
  assign _152_ = _121_ ? _140_ : io_out;
  assign _153_ = _121_ ? _141_ : io_dir;
  assign _154_ = _104_ ? 1'h0 : _142_;
  assign _155_ = _104_ ? _066_ : _143_;
  assign _156_ = _104_ ? _067_ : _144_;
  assign _157_ = _104_ ? _068_ : _145_;
  assign _158_ = _104_ ? 1'h0 : _146_;
  assign _159_ = _104_ ? 1'h0 : _147_;
  assign _160_ = _104_ ? _071_ : _148_;
  assign _161_ = _104_ ? _072_ : _149_;
  assign _162_ = _104_ ? _073_ : _150_;
  assign _163_ = _104_ ? _074_ : _151_;
  assign _000_ = _104_ ? { _119_, _118_, _117_, _116_ } : dataout;
  assign _001_ = _020_ ? _120_ : new_pos;
  assign _002_ = _104_ ? io_out : _152_;
  assign _003_ = _104_ ? io_dir : _153_;
  assign _004_ = sck_fall ? dataout[31] : _064_;
  assign _005_ = sck_fall ? { dataout[30:0], 1'h0 } : dataout;
  assign _006_ = sck_rise ? _064_ : _004_;
  assign _007_ = sck_rise ? _154_ : 1'h0;
  assign _008_ = sck_rise ? _155_ : _066_;
  assign _009_ = sck_rise ? _156_ : _067_;
  assign _010_ = sck_rise ? _157_ : _068_;
  assign _011_ = sck_rise ? _158_ : 1'h0;
  assign _012_ = sck_rise ? _159_ : 1'h0;
  assign _013_ = sck_rise ? _160_ : _071_;
  assign _014_ = sck_rise ? _161_ : _072_;
  assign _015_ = sck_rise ? _162_ : _073_;
  assign _016_ = sck_rise ? _163_ : _074_;
  assign _017_ = sck_rise ? _000_ : _005_;
  assign _018_ = sck_rise ? { datain[38:0], rx } : datain;
  assign _019_ = sck_rise ? _103_ : bit_counter;
  assign _020_ = _104_ & sck_rise;
  assign _021_ = sck_rise ? _002_ : io_out;
  assign _022_ = sck_rise ? _003_ : io_dir;
  assign _023_ = cs_fall ? _064_ : _006_;
  assign _024_ = cs_fall ? 1'h0 : _007_;
  assign _025_ = cs_fall ? _066_ : _008_;
  assign _026_ = cs_fall ? _067_ : _009_;
  assign _027_ = cs_fall ? _068_ : _010_;
  assign _028_ = cs_fall ? 1'h0 : _011_;
  assign _029_ = cs_fall ? 1'h0 : _012_;
  assign _030_ = cs_fall ? _071_ : _013_;
  assign _031_ = cs_fall ? _072_ : _014_;
  assign _032_ = cs_fall ? _073_ : _015_;
  assign _033_ = cs_fall ? _074_ : _016_;
  assign _034_ = cs_fall ? dataout : _017_;
  assign _035_ = cs_fall ? datain : _018_;
  assign _036_ = cs_fall ? 6'h00 : _019_;
  assign _037_ = cs_fall ? new_pos : _001_;
  assign _038_ = cs_fall ? io_out : _021_;
  assign _039_ = cs_fall ? io_dir : _022_;
  assign _040_ = rst_i ? _064_ : _023_;
  assign _041_ = rst_i ? 1'h0 : _024_;
  assign _042_ = rst_i ? 32'd0 : _025_;
  assign _043_ = rst_i ? 32'd0 : _026_;
  assign _044_ = rst_i ? 26'h0000000 : _027_;
  assign _045_ = rst_i ? 1'h0 : _028_;
  assign _046_ = rst_i ? 1'h0 : _029_;
  assign _047_ = rst_i ? 8'h00 : _030_;
  assign _048_ = rst_i ? 6'h00 : _031_;
  assign _049_ = rst_i ? 6'h00 : _032_;
  assign _050_ = rst_i ? 6'h00 : _033_;
  assign _051_ = rst_i ? 32'd0 : _034_;
  assign _052_ = rst_i ? datain : _035_;
  assign _053_ = rst_i ? bit_counter : _036_;
  assign _054_ = rst_i ? 8'h00 : n_over;
  assign _055_ = rst_i ? 1'h0 : _037_;
  assign _056_ = rst_i ? 6'h00 : _038_;
  assign _057_ = rst_i ? io_dir : _039_;
  assign _058_ = n_over + 8'h01;
  assign _059_ = _060_ ? _058_ : _054_;
  assign _060_ = new_pos & pos_valid_i;
  assign _061_ = pos_valid_i ? 1'h1 : _055_;
  assign _062_ = trig_i ? io_dir : _049_;
  assign _063_ = trig_i ? io_out : _050_;
  always @(posedge clk_i)
    _064_ <= _040_;
  always @(posedge clk_i)
    _065_ <= _041_;
  always @(posedge clk_i)
    _066_ <= _042_;
  always @(posedge clk_i)
    _067_ <= _043_;
  always @(posedge clk_i)
    _068_ <= _044_;
  always @(posedge clk_i)
    _069_ <= _045_;
  always @(posedge clk_i)
    _070_ <= _046_;
  always @(posedge clk_i)
    _071_ <= _047_;
  always @(posedge clk_i)
    _072_ <= _048_;
  always @(posedge clk_i)
    _073_ <= _062_;
  always @(posedge clk_i)
    _074_ <= _063_;
  always @(posedge clk_i)
    _075_ <= _051_;
  always @(posedge clk_i)
    _076_ <= _052_;
  always @(posedge clk_i)
    _077_ <= cs;
  always @(posedge clk_i)
    _078_ <= sck;
  always @(posedge clk_i)
    _079_ <= _053_;
  always @(posedge clk_i)
    _080_ <= _101_;
  always @(posedge clk_i)
    _081_ <= _059_;
  always @(posedge clk_i)
    _082_ <= _102_;
  always @(posedge clk_i)
    _083_ <= _061_;
  always @(posedge clk_i)
    _084_ <= _056_;
  always @(posedge clk_i)
    _085_ <= _057_;
  assign _086_ = trig_i ? io_in_i : io_in;
  always @(posedge clk_i)
    _087_ <= _086_;
  assign _091_ = ~ cs;
  assign _092_ = cs_prev & _091_;
  assign _093_ = ~ sck;
  assign _094_ = sck_prev & _093_;
  assign _095_ = ~ sck_prev;
  assign _096_ = _095_ & sck;
  assign _097_ = n_pos + 16'h0001;
  assign _098_ = pos_valid_i ? _097_ : n_pos;
  assign _099_ = n_err + 8'h01;
  assign _100_ = error_event_i ? _099_ : n_err;
  assign _101_ = rst_i ? 8'h00 : _100_;
  assign _102_ = rst_i ? 16'h0000 : _098_;
  assign _103_ = bit_counter + 6'h01;
  assign _104_ = bit_counter == 6'h07;
  assign _105_ = { datain[6:0], rx } == 8'h00;
  assign _106_ = { datain[6:0], rx } == 8'h01;
  assign _107_ = { datain[6:0], rx } == 8'h02;
  assign _108_ = { datain[6:0], rx } == 8'h03;
  assign _109_ = { datain[6:0], rx } == 8'h04;
  assign _110_ = { datain[6:0], rx } == 8'h05;
  sync_bit_Brtl sync_cs_inst (
    .bit_i(cs_i),
    .bit_o(_089_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_rx_inst (
    .bit_i(rx_i),
    .bit_o(_090_),
    .clk_i(clk_i)
  );
  sync_bit_Brtl sync_sck_inst (
    .bit_i(sck_i),
    .bit_o(_088_),
    .clk_i(clk_i)
  );
  assign dataout = _075_;
  assign datain = _076_;
  assign cs_prev = _077_;
  assign cs_fall = _092_;
  assign sck_prev = _078_;
  assign sck_fall = _094_;
  assign sck_rise = _096_;
  assign sck = _088_;
  assign cs = _089_;
  assign rx = _090_;
  assign bit_counter = _079_;
  assign n_err = _080_;
  assign n_over = _081_;
  assign n_pos = _082_;
  assign new_pos = _083_;
  assign io_out = _084_;
  assign io_dir = _085_;
  assign io_in = _087_;
  assign tx_o = _064_;
  assign override_trig_o = _065_;
  assign ntrig_o = _066_;
  assign trig_period_o = _067_;
  assign width_o = _068_;
  assign pos_req_o = _069_;
  assign acq_start_o = _070_;
  assign bissc_half_clk_period_o = _071_;
  assign bissc_n_rising_edges_o = _072_;
  assign io_dir_o = _073_;
  assign io_out_o = _074_;
endmodule

module sync_bit_Brtl(clk_i, bit_i, bit_o);
  input clk_i;
  wire clk_i;
  input bit_i;
  wire bit_i;
  output bit_o;
  wire bit_o;
  reg _0_;
  reg _1_ = 1'h0;
  wire bit_meta;
  always @(posedge clk_i)
    _0_ <= bit_meta;
  always @(posedge clk_i)
    _1_ <= bit_i;
  assign bit_meta = _1_;
  assign bit_o = _0_;
endmodule

module trigger_generator_Brtl(clk_i, rst_i, go_i, trig_period_i, ntrig_i, busy_o, trig_o);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input go_i;
  wire go_i;
  input [31:0] trig_period_i;
  wire [31:0] trig_period_i;
  input [31:0] ntrig_i;
  wire [31:0] ntrig_i;
  output busy_o;
  wire busy_o;
  output trig_o;
  wire trig_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire [31:0] _07_;
  wire _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire _11_;
  wire [31:0] _12_;
  wire [31:0] _13_;
  wire _14_;
  wire _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  wire _18_;
  wire _19_;
  wire [31:0] _20_;
  wire [31:0] _21_;
  wire _22_;
  reg _23_;
  reg _24_;
  reg [31:0] _25_;
  reg [31:0] _26_;
  reg _27_;
  wire running;
  wire [31:0] trig_count;
  wire [31:0] trig_timer;
  assign _00_ = running | go_i;
  assign _01_ = trig_timer == 32'd0;
  assign _02_ = trig_count == 32'd0;
  assign _03_ = trig_count - 32'd1;
  assign _04_ = _02_ ? trig_timer : trig_period_i;
  assign _05_ = _02_ ? trig_count : _03_;
  assign _06_ = _11_ ? 1'h0 : running;
  assign _07_ = trig_timer - 32'd1;
  assign _08_ = _01_ ? 1'h1 : 1'h0;
  assign _09_ = _01_ ? _04_ : _07_;
  assign _10_ = _01_ ? _05_ : trig_count;
  assign _11_ = _02_ & _01_;
  assign _12_ = go_i ? trig_period_i : trig_timer;
  assign _13_ = go_i ? ntrig_i : trig_count;
  assign _14_ = go_i ? 1'h1 : running;
  assign _15_ = running ? _08_ : 1'h0;
  assign _16_ = running ? _09_ : _12_;
  assign _17_ = running ? _10_ : _13_;
  assign _18_ = running ? _06_ : _14_;
  assign _19_ = rst_i ? 1'h0 : _15_;
  assign _20_ = rst_i ? 32'd0 : _16_;
  assign _21_ = rst_i ? 32'd0 : _17_;
  assign _22_ = rst_i ? 1'h0 : _18_;
  always @(posedge clk_i)
    _23_ <= _00_;
  always @(posedge clk_i)
    _24_ <= _19_;
  always @(posedge clk_i)
    _25_ <= _20_;
  always @(posedge clk_i)
    _26_ <= _21_;
  always @(posedge clk_i)
    _27_ <= _22_;
  assign trig_timer = _25_;
  assign trig_count = _26_;
  assign running = _27_;
  assign busy_o = _23_;
  assign trig_o = _24_;
endmodule

module tt_um_emiliopeju_lightscan(clk, ui_in, uio_in, ena, rst_n, uo_out, uio_out, uio_oe);
  input clk;
  wire clk;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  input ena;
  wire ena;
  input rst_n;
  wire rst_n;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [5:0] _03_;
  wire [5:0] _04_;
  wire [5:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [50:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [31:0] _19_;
  wire [31:0] _20_;
  wire [25:0] _21_;
  wire _22_;
  wire acq_start;
  wire biss_data_sync;
  wire bissc_go;
  wire [7:0] bissc_half_clk_period;
  wire [5:0] bissc_n_rising_edges;
  wire [31:0] ntrig;
  wire override_trig;
  wire [50:0] pos;
  wire pos_err;
  wire pos_req;
  wire pos_valid;
  wire rst;
  wire trig;
  wire trig_from_pulser;
  wire [31:0] trig_period;
  wire [25:0] width;
  assign _00_ = ~ rst_n;
  assign _11_ = pos_req | trig;
  assign _16_ = trig_from_pulser | override_trig;
  bissc_Barch bissc_inst (
    .clk_i(clk),
    .clk_o(_15_),
    .data_i(biss_data_sync),
    .err_o(_14_),
    .go_i(bissc_go),
    .half_clk_period_i(bissc_half_clk_period),
    .n_rising_edges_i(bissc_n_rising_edges),
    .pos_o(_12_),
    .rst_i(rst),
    .valid_o(_13_)
  );
  deglitcher_Brtl_3 deglitcher_inst (
    .bit_i(biss_data_sync),
    .bit_o(_10_),
    .clk_i(clk)
  );
  pulsed_trigger_Brtl pulsed_trigger_inst (
    .busy_o(_06_),
    .clk_i(clk),
    .go_i(acq_start),
    .ntrig_i(ntrig),
    .pulse_o(_08_),
    .rst_i(rst),
    .trig_o(_07_),
    .trig_period_i(trig_period),
    .width_i(width)
  );
  spi_registers_Brtl reg_inst (
    .acq_start_o(_01_),
    .bissc_half_clk_period_o(_02_),
    .bissc_n_rising_edges_o(_03_),
    .clk_i(clk),
    .cs_i(ui_in[0]),
    .error_event_i(pos_err),
    .io_dir_o(_04_),
    .io_in_i(uio_in[7:2]),
    .io_out_o(_05_),
    .ntrig_o(_19_),
    .override_trig_o(_18_),
    .pos_i(pos),
    .pos_req_o(_22_),
    .pos_valid_i(pos_valid),
    .rst_i(rst),
    .rx_i(ui_in[2]),
    .sck_i(ui_in[1]),
    .trig_i(trig),
    .trig_period_o(_20_),
    .tx_o(_17_),
    .width_o(_21_)
  );
  sync_bit_Brtl sync_biss_data_inst (
    .bit_i(uio_in[1]),
    .bit_o(_09_),
    .clk_i(clk)
  );
  assign pos = _12_;
  assign pos_valid = _13_;
  assign pos_err = _14_;
  assign pos_req = _22_;
  assign rst = _00_;
  assign biss_data_sync = _09_;
  assign bissc_go = _11_;
  assign acq_start = _01_;
  assign trig = _16_;
  assign trig_from_pulser = _07_;
  assign override_trig = _18_;
  assign trig_period = _20_;
  assign ntrig = _19_;
  assign width = _21_;
  assign bissc_half_clk_period = _02_;
  assign bissc_n_rising_edges = _03_;
  assign uo_out = { 4'hz, _17_, pos_valid, _08_, _06_ };
  assign uio_out = { _05_, 1'hz, _15_ };
  assign uio_oe = { _04_, 2'h1 };
endmodule
